### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
  id: AzureEventBusReceiverModule`1
  parent: Cqrs.Azure.EventHub.EventBus.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: AzureEventBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventBusReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureEventBusReceiverModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventBusReceiverModule.cs
    startLine: 19
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
  namespace: Cqrs.Azure.EventHub.EventBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureEventBusReceiver%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Events.IEventReceiver\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureEventBusReceiverModule<TAuthenticationToken> : AzureEventHubReceiverModule<TAuthenticationToken>'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureEventBusReceiverModule(Of TAuthenticationToken)
          Inherits AzureEventHubReceiverModule(Of TAuthenticationToken)
  inheritance:
  - System.Object
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}
  inheritedMembers:
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}.Load
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}.RegisterEventHandlerRegistrar
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}.RegisterEventMessageSerialiser
  nameWithType.vb: AzureEventBusReceiverModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventBusReceiverModule(Of TAuthenticationToken)
references:
- uid: Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
  isExternal: false
  name: AzureEventBusReceiver<TAuthenticationToken>
  nameWithType: AzureEventBusReceiver<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureEventBusReceiver<TAuthenticationToken>
  nameWithType.vb: AzureEventBusReceiver(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureEventBusReceiver(Of TAuthenticationToken)
  name.vb: AzureEventBusReceiver(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
    name: AzureEventBusReceiver
    nameWithType: AzureEventBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusReceiver
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
    name: AzureEventBusReceiver
    nameWithType: AzureEventBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusReceiver
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Events.IEventReceiver
  commentId: T:Cqrs.Events.IEventReceiver
  parent: Cqrs.Events
  isExternal: false
  name: IEventReceiver
  nameWithType: IEventReceiver
  fullName: Cqrs.Events.IEventReceiver
- uid: Cqrs.Azure.EventHub.EventBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.EventBus.Configuration
  isExternal: false
  name: Cqrs.Azure.EventHub.EventBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.EventBus.Configuration
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{`0}
  parent: Cqrs.Azure.EventHub.EventBus.Configuration
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  name: AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
    name: AzureEventHubReceiverModule
    nameWithType: AzureEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
    name: AzureEventHubReceiverModule
    nameWithType: AzureEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}.Load
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{`0}.Load
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  name: Load()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.Load()
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).Load()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).Load()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureEventHubReceiverModule(Of TAuthenticationToken).Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}.RegisterEventHandlerRegistrar
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{`0}.RegisterEventHandlerRegistrar
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  name: RegisterEventHandlerRegistrar()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar()
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
    name: RegisterEventHandlerRegistrar
    nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
    name: RegisterEventHandlerRegistrar
    nameWithType: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}.RegisterEventMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{`0}.RegisterEventMessageSerialiser
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  name: RegisterEventMessageSerialiser()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Events
  commentId: N:Cqrs.Events
  isExternal: false
  name: Cqrs.Events
  nameWithType: Cqrs.Events
  fullName: Cqrs.Events
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  isExternal: false
  name: AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
    name: AzureEventHubReceiverModule
    nameWithType: AzureEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
    name: AzureEventHubReceiverModule
    nameWithType: AzureEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  isExternal: false
  name: Load()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.Load()
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).Load()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).Load()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureEventHubReceiverModule(Of TAuthenticationToken).Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  isExternal: false
  name: RegisterEventHandlerRegistrar()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar()
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
    name: RegisterEventHandlerRegistrar
    nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
    name: RegisterEventHandlerRegistrar
    nameWithType: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  isExternal: false
  name: RegisterEventMessageSerialiser()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
