### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule
  commentId: T:Cqrs.Ninject.Mongo.Configuration.MongoModule
  id: MongoModule
  parent: Cqrs.Ninject.Mongo.Configuration
  children:
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  langs:
  - csharp
  - vb
  name: MongoModule
  nameWithType: MongoModule
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule
  type: Class
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: MongoModule
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
    startLine: 16
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Mongo.Factories.MongoDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class MongoModule : NinjectModule'
    content.vb: >-
      Public Class MongoModule
          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  id: Load
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: MongoModule.Load()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
    startLine: 23
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  id: RegisterServices
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  langs:
  - csharp
  - vb
  name: RegisterServices()
  nameWithType: MongoModule.RegisterServices()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterServices
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
    startLine: 35
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nRegister the all services\n"
  example: []
  syntax:
    content: public virtual void RegisterServices()
    content.vb: Public Overridable Sub RegisterServices
  overload: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  id: RegisterFactories
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  langs:
  - csharp
  - vb
  name: RegisterFactories()
  nameWithType: MongoModule.RegisterFactories()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterFactories
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
    startLine: 42
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nRegister the all factories\n"
  example: []
  syntax:
    content: public virtual void RegisterFactories()
    content.vb: Public Overridable Sub RegisterFactories
  overload: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  id: RegisterCqrsRequirements
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  langs:
  - csharp
  - vb
  name: RegisterCqrsRequirements()
  nameWithType: MongoModule.RegisterCqrsRequirements()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterCqrsRequirements
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/MongoModule.cs
    startLine: 52
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nRegister any CQRS requirements\n"
  example: []
  syntax:
    content: public virtual void RegisterCqrsRequirements()
    content.vb: Public Overridable Sub RegisterCqrsRequirements
  overload: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Cqrs.Mongo.Factories.MongoDataStoreConnectionStringFactory
  commentId: T:Cqrs.Mongo.Factories.MongoDataStoreConnectionStringFactory
  isExternal: false
  name: MongoDataStoreConnectionStringFactory
  nameWithType: MongoDataStoreConnectionStringFactory
  fullName: Cqrs.Mongo.Factories.MongoDataStoreConnectionStringFactory
- uid: Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory
  commentId: T:Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory
  parent: Cqrs.Mongo.Factories
  isExternal: false
  name: IMongoDataStoreConnectionStringFactory
  nameWithType: IMongoDataStoreConnectionStringFactory
  fullName: Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory
- uid: Cqrs.Ninject.Mongo.Configuration
  commentId: N:Cqrs.Ninject.Mongo.Configuration
  isExternal: false
  name: Cqrs.Ninject.Mongo.Configuration
  nameWithType: Cqrs.Ninject.Mongo.Configuration
  fullName: Cqrs.Ninject.Mongo.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Mongo.Factories
  commentId: N:Cqrs.Mongo.Factories
  isExternal: false
  name: Cqrs.Mongo.Factories
  nameWithType: Cqrs.Mongo.Factories
  fullName: Cqrs.Mongo.Factories
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load*
  commentId: Overload:Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  isExternal: false
  name: Load
  nameWithType: MongoModule.Load
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices*
  commentId: Overload:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  isExternal: false
  name: RegisterServices
  nameWithType: MongoModule.RegisterServices
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories*
  commentId: Overload:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  isExternal: false
  name: RegisterFactories
  nameWithType: MongoModule.RegisterFactories
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements*
  commentId: Overload:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  isExternal: false
  name: RegisterCqrsRequirements
  nameWithType: MongoModule.RegisterCqrsRequirements
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
