### YamlMime:ManagedReference
items:
- uid: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  commentId: T:Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  id: WcfDataContractResolverConfiguration.RegistrationHandling
  parent: Cqrs.Services
  children:
  - Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Nothing
  - Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Replace
  - Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.ThrowExceptionOnDuplicate
  langs:
  - csharp
  - vb
  name: WcfDataContractResolverConfiguration.RegistrationHandling
  nameWithType: WcfDataContractResolverConfiguration.RegistrationHandling
  fullName: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  type: Enum
  source:
    remote:
      path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegistrationHandling
    path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
    startLine: 117
  assemblies:
  - Cqrs
  namespace: Cqrs.Services
  summary: "\nThe type of registration action to take\n"
  example: []
  syntax:
    content: public enum RegistrationHandling
    content.vb: Public Enum RegistrationHandling
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Replace
  commentId: F:Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Replace
  id: Replace
  parent: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  langs:
  - csharp
  - vb
  name: Replace
  nameWithType: WcfDataContractResolverConfiguration.RegistrationHandling.Replace
  fullName: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Replace
  type: Field
  source:
    remote:
      path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Replace
    path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
    startLine: 122
  assemblies:
  - Cqrs
  namespace: Cqrs.Services
  summary: "\nAdd any new, and replace any existing.\n"
  example: []
  syntax:
    content: Replace = 0
    return:
      type: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.ThrowExceptionOnDuplicate
  commentId: F:Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.ThrowExceptionOnDuplicate
  id: ThrowExceptionOnDuplicate
  parent: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  langs:
  - csharp
  - vb
  name: ThrowExceptionOnDuplicate
  nameWithType: WcfDataContractResolverConfiguration.RegistrationHandling.ThrowExceptionOnDuplicate
  fullName: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.ThrowExceptionOnDuplicate
  type: Field
  source:
    remote:
      path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: ThrowExceptionOnDuplicate
    path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
    startLine: 127
  assemblies:
  - Cqrs
  namespace: Cqrs.Services
  summary: "\nThrow an <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref> if one already exists.\n"
  example: []
  syntax:
    content: ThrowExceptionOnDuplicate = 1
    return:
      type: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Nothing
  commentId: F:Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Nothing
  id: Nothing
  parent: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  langs:
  - csharp
  - vb
  name: Nothing
  nameWithType: WcfDataContractResolverConfiguration.RegistrationHandling.Nothing
  fullName: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling.Nothing
  type: Field
  source:
    remote:
      path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Nothing
    path: Framework/Cqrs/Services/WcfDataContractResolverConfiguration.cs
    startLine: 132
  assemblies:
  - Cqrs
  namespace: Cqrs.Services
  summary: "\nKeep the existing one and don&apos;t do anything.\n"
  example: []
  syntax:
    content: Nothing = 2
    return:
      type: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Cqrs.Services
  commentId: N:Cqrs.Services
  isExternal: false
  name: Cqrs.Services
  nameWithType: Cqrs.Services
  fullName: Cqrs.Services
- uid: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  commentId: T:Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
  parent: Cqrs.Services
  isExternal: false
  name: WcfDataContractResolverConfiguration.RegistrationHandling
  nameWithType: WcfDataContractResolverConfiguration.RegistrationHandling
  fullName: Cqrs.Services.WcfDataContractResolverConfiguration.RegistrationHandling
- uid: System.Exception
  commentId: T:System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
