### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.WebApi.Configuration
  commentId: N:Cqrs.Ninject.WebApi.Configuration
  id: Cqrs.Ninject.WebApi.Configuration
  children:
  - Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  - Cqrs.Ninject.WebApi.Configuration.WebApiModule
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.WebApi.Configuration
  nameWithType: Cqrs.Ninject.WebApi.Configuration
  fullName: Cqrs.Ninject.WebApi.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.WebApi
references:
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  commentId: T:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  isExternal: false
  name: SimplifiedNinjectWebApi
  nameWithType: SimplifiedNinjectWebApi
  fullName: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
- uid: Cqrs.Ninject.WebApi.Configuration.WebApiModule
  commentId: T:Cqrs.Ninject.WebApi.Configuration.WebApiModule
  isExternal: false
  name: WebApiModule
  nameWithType: WebApiModule
  fullName: Cqrs.Ninject.WebApi.Configuration.WebApiModule
