### YamlMime:ManagedReference
items:
- uid: Cqrs.Akka.Configuration.IHandlerResolver
  commentId: T:Cqrs.Akka.Configuration.IHandlerResolver
  id: IHandlerResolver
  parent: Cqrs.Akka.Configuration
  children:
  - Cqrs.Akka.Configuration.IHandlerResolver.Resolve(System.Type,System.Object)
  langs:
  - csharp
  - vb
  name: IHandlerResolver
  nameWithType: IHandlerResolver
  fullName: Cqrs.Akka.Configuration.IHandlerResolver
  type: Interface
  source:
    remote:
      path: Framework/Akka.Net/Cqrs.Akka/Configuration/IHandlerResolver.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: IHandlerResolver
    path: Framework/Akka.Net/Cqrs.Akka/Configuration/IHandlerResolver.cs
    startLine: 15
  assemblies:
  - Cqrs.Akka
  namespace: Cqrs.Akka.Configuration
  summary: "\nResolves handlers for use with Akka.Net\n"
  example: []
  syntax:
    content: public interface IHandlerResolver
    content.vb: Public Interface IHandlerResolver
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Cqrs.Akka.Configuration.IHandlerResolver.Resolve(System.Type,System.Object)
  commentId: M:Cqrs.Akka.Configuration.IHandlerResolver.Resolve(System.Type,System.Object)
  id: Resolve(System.Type,System.Object)
  parent: Cqrs.Akka.Configuration.IHandlerResolver
  langs:
  - csharp
  - vb
  name: Resolve(Type, Object)
  nameWithType: IHandlerResolver.Resolve(Type, Object)
  fullName: Cqrs.Akka.Configuration.IHandlerResolver.Resolve(System.Type, System.Object)
  type: Method
  source:
    remote:
      path: Framework/Akka.Net/Cqrs.Akka/Configuration/IHandlerResolver.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Resolve
    path: Framework/Akka.Net/Cqrs.Akka/Configuration/IHandlerResolver.cs
    startLine: 20
  assemblies:
  - Cqrs.Akka
  namespace: Cqrs.Akka.Configuration
  summary: "\nResolves instances of <code data-dev-comment-type=\"paramref\">handerType</code>.\n"
  example: []
  syntax:
    content: object Resolve(Type handerType, object rsn)
    parameters:
    - id: handerType
      type: System.Type
    - id: rsn
      type: System.Object
    return:
      type: System.Object
    content.vb: Function Resolve(handerType As Type, rsn As Object) As Object
  overload: Cqrs.Akka.Configuration.IHandlerResolver.Resolve*
references:
- uid: Cqrs.Akka.Configuration
  commentId: N:Cqrs.Akka.Configuration
  isExternal: false
  name: Cqrs.Akka.Configuration
  nameWithType: Cqrs.Akka.Configuration
  fullName: Cqrs.Akka.Configuration
- uid: Cqrs.Akka.Configuration.IHandlerResolver.Resolve*
  commentId: Overload:Cqrs.Akka.Configuration.IHandlerResolver.Resolve
  isExternal: false
  name: Resolve
  nameWithType: IHandlerResolver.Resolve
  fullName: Cqrs.Akka.Configuration.IHandlerResolver.Resolve
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
