### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Configuration
  commentId: N:Cqrs.Ninject.Configuration
  id: Cqrs.Ninject.Configuration
  children:
  - Cqrs.Ninject.Configuration.CqrsModule`2
  - Cqrs.Ninject.Configuration.EventStoreModule`1
  - Cqrs.Ninject.Configuration.InProcessCommandBusModule`1
  - Cqrs.Ninject.Configuration.InProcessEventBusModule`1
  - Cqrs.Ninject.Configuration.InProcessEventStoreModule`1
  - Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule`1
  - Cqrs.Ninject.Configuration.NinjectDependencyResolver
  - Cqrs.Ninject.Configuration.ResolvableModule
  - Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp`1
  - Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Configuration
  nameWithType: Cqrs.Ninject.Configuration
  fullName: Cqrs.Ninject.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject
references:
- uid: Cqrs.Ninject.Configuration.InProcessCommandBusModule`1
  commentId: T:Cqrs.Ninject.Configuration.InProcessCommandBusModule`1
  isExternal: false
  name: InProcessCommandBusModule<TAuthenticationToken>
  nameWithType: InProcessCommandBusModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.InProcessCommandBusModule<TAuthenticationToken>
  nameWithType.vb: InProcessCommandBusModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.InProcessCommandBusModule(Of TAuthenticationToken)
  name.vb: InProcessCommandBusModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.InProcessCommandBusModule`1
    name: InProcessCommandBusModule
    nameWithType: InProcessCommandBusModule
    fullName: Cqrs.Ninject.Configuration.InProcessCommandBusModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.InProcessCommandBusModule`1
    name: InProcessCommandBusModule
    nameWithType: InProcessCommandBusModule
    fullName: Cqrs.Ninject.Configuration.InProcessCommandBusModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.InProcessEventBusModule`1
  commentId: T:Cqrs.Ninject.Configuration.InProcessEventBusModule`1
  isExternal: false
  name: InProcessEventBusModule<TAuthenticationToken>
  nameWithType: InProcessEventBusModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.InProcessEventBusModule<TAuthenticationToken>
  nameWithType.vb: InProcessEventBusModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.InProcessEventBusModule(Of TAuthenticationToken)
  name.vb: InProcessEventBusModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.InProcessEventBusModule`1
    name: InProcessEventBusModule
    nameWithType: InProcessEventBusModule
    fullName: Cqrs.Ninject.Configuration.InProcessEventBusModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.InProcessEventBusModule`1
    name: InProcessEventBusModule
    nameWithType: InProcessEventBusModule
    fullName: Cqrs.Ninject.Configuration.InProcessEventBusModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.InProcessEventStoreModule`1
  commentId: T:Cqrs.Ninject.Configuration.InProcessEventStoreModule`1
  isExternal: false
  name: InProcessEventStoreModule<TAuthenticationToken>
  nameWithType: InProcessEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.InProcessEventStoreModule<TAuthenticationToken>
  nameWithType.vb: InProcessEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.InProcessEventStoreModule(Of TAuthenticationToken)
  name.vb: InProcessEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.InProcessEventStoreModule`1
    name: InProcessEventStoreModule
    nameWithType: InProcessEventStoreModule
    fullName: Cqrs.Ninject.Configuration.InProcessEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.InProcessEventStoreModule`1
    name: InProcessEventStoreModule
    nameWithType: InProcessEventStoreModule
    fullName: Cqrs.Ninject.Configuration.InProcessEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.ResolvableModule
  commentId: T:Cqrs.Ninject.Configuration.ResolvableModule
  parent: Cqrs.Ninject.Configuration
  isExternal: false
  name: ResolvableModule
  nameWithType: ResolvableModule
  fullName: Cqrs.Ninject.Configuration.ResolvableModule
- uid: Cqrs.Ninject.Configuration.CqrsModule`2
  commentId: T:Cqrs.Ninject.Configuration.CqrsModule`2
  isExternal: false
  name: CqrsModule<TAuthenticationToken, TAuthenticationTokenHelper>
  nameWithType: CqrsModule<TAuthenticationToken, TAuthenticationTokenHelper>
  fullName: Cqrs.Ninject.Configuration.CqrsModule<TAuthenticationToken, TAuthenticationTokenHelper>
  nameWithType.vb: CqrsModule(Of TAuthenticationToken, TAuthenticationTokenHelper)
  fullName.vb: Cqrs.Ninject.Configuration.CqrsModule(Of TAuthenticationToken, TAuthenticationTokenHelper)
  name.vb: CqrsModule(Of TAuthenticationToken, TAuthenticationTokenHelper)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.CqrsModule`2
    name: CqrsModule
    nameWithType: CqrsModule
    fullName: Cqrs.Ninject.Configuration.CqrsModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TAuthenticationTokenHelper
    nameWithType: TAuthenticationTokenHelper
    fullName: TAuthenticationTokenHelper
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.CqrsModule`2
    name: CqrsModule
    nameWithType: CqrsModule
    fullName: Cqrs.Ninject.Configuration.CqrsModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TAuthenticationTokenHelper
    nameWithType: TAuthenticationTokenHelper
    fullName: TAuthenticationTokenHelper
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule`1
  commentId: T:Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule`1
  isExternal: false
  name: MemoryCacheEventStoreModule<TAuthenticationToken>
  nameWithType: MemoryCacheEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule<TAuthenticationToken>
  nameWithType.vb: MemoryCacheEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule(Of TAuthenticationToken)
  name.vb: MemoryCacheEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule`1
    name: MemoryCacheEventStoreModule
    nameWithType: MemoryCacheEventStoreModule
    fullName: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule`1
    name: MemoryCacheEventStoreModule
    nameWithType: MemoryCacheEventStoreModule
    fullName: Cqrs.Ninject.Configuration.MemoryCacheEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp`1
  commentId: T:Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp`1
  isExternal: false
  name: SimplifiedNinjectStartUp<THostModule>
  nameWithType: SimplifiedNinjectStartUp<THostModule>
  fullName: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp<THostModule>
  nameWithType.vb: SimplifiedNinjectStartUp(Of THostModule)
  fullName.vb: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp(Of THostModule)
  name.vb: SimplifiedNinjectStartUp(Of THostModule)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp`1
    name: SimplifiedNinjectStartUp
    nameWithType: SimplifiedNinjectStartUp
    fullName: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp
  - name: <
    nameWithType: <
    fullName: <
  - name: THostModule
    nameWithType: THostModule
    fullName: THostModule
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp`1
    name: SimplifiedNinjectStartUp
    nameWithType: SimplifiedNinjectStartUp
    fullName: Cqrs.Ninject.Configuration.SimplifiedNinjectStartUp
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: THostModule
    nameWithType: THostModule
    fullName: THostModule
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
  commentId: T:Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
  isExternal: false
  name: SimplifiedSqlModule<TAuthenticationToken>
  nameWithType: SimplifiedSqlModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.SimplifiedSqlModule<TAuthenticationToken>
  nameWithType.vb: SimplifiedSqlModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.SimplifiedSqlModule(Of TAuthenticationToken)
  name.vb: SimplifiedSqlModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
    name: SimplifiedSqlModule
    nameWithType: SimplifiedSqlModule
    fullName: Cqrs.Ninject.Configuration.SimplifiedSqlModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
    name: SimplifiedSqlModule
    nameWithType: SimplifiedSqlModule
    fullName: Cqrs.Ninject.Configuration.SimplifiedSqlModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.NinjectDependencyResolver
  commentId: T:Cqrs.Ninject.Configuration.NinjectDependencyResolver
  parent: Cqrs.Ninject.Configuration
  isExternal: false
  name: NinjectDependencyResolver
  nameWithType: NinjectDependencyResolver
  fullName: Cqrs.Ninject.Configuration.NinjectDependencyResolver
- uid: Cqrs.Ninject.Configuration.EventStoreModule`1
  commentId: T:Cqrs.Ninject.Configuration.EventStoreModule`1
  isExternal: false
  name: EventStoreModule<TAuthenticationToken>
  nameWithType: EventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.EventStoreModule<TAuthenticationToken>
  nameWithType.vb: EventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.EventStoreModule(Of TAuthenticationToken)
  name.vb: EventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.EventStoreModule`1
    name: EventStoreModule
    nameWithType: EventStoreModule
    fullName: Cqrs.Ninject.Configuration.EventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.EventStoreModule`1
    name: EventStoreModule
    nameWithType: EventStoreModule
    fullName: Cqrs.Ninject.Configuration.EventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration
  commentId: N:Cqrs.Ninject.Configuration
  isExternal: false
  name: Cqrs.Ninject.Configuration
  nameWithType: Cqrs.Ninject.Configuration
  fullName: Cqrs.Ninject.Configuration
