### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.MongoDB.Configuration
  commentId: N:Cqrs.Ninject.MongoDB.Configuration
  id: Cqrs.Ninject.MongoDB.Configuration
  children:
  - Cqrs.Ninject.MongoDB.Configuration.MongoDbDataStoreModule
  - Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule`1
  - Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.MongoDB.Configuration
  nameWithType: Cqrs.Ninject.MongoDB.Configuration
  fullName: Cqrs.Ninject.MongoDB.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.MongoDB
references:
- uid: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule`1
  commentId: T:Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule`1
  isExternal: false
  name: MongoDbEventStoreModule<TAuthenticationToken>
  nameWithType: MongoDbEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule<TAuthenticationToken>
  nameWithType.vb: MongoDbEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule(Of TAuthenticationToken)
  name.vb: MongoDbEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule`1
    name: MongoDbEventStoreModule
    nameWithType: MongoDbEventStoreModule
    fullName: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule`1
    name: MongoDbEventStoreModule
    nameWithType: MongoDbEventStoreModule
    fullName: Cqrs.Ninject.MongoDB.Configuration.MongoDbEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.MongoDB.Configuration.MongoDbDataStoreModule
  commentId: T:Cqrs.Ninject.MongoDB.Configuration.MongoDbDataStoreModule
  isExternal: false
  name: MongoDbDataStoreModule
  nameWithType: MongoDbDataStoreModule
  fullName: Cqrs.Ninject.MongoDB.Configuration.MongoDbDataStoreModule
- uid: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule`1
  commentId: T:Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule`1
  isExternal: false
  name: TestMongoDbDataStoreModule<TAuthenticationToken>
  nameWithType: TestMongoDbDataStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule<TAuthenticationToken>
  nameWithType.vb: TestMongoDbDataStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule(Of TAuthenticationToken)
  name.vb: TestMongoDbDataStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule`1
    name: TestMongoDbDataStoreModule
    nameWithType: TestMongoDbDataStoreModule
    fullName: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule`1
    name: TestMongoDbDataStoreModule
    nameWithType: TestMongoDbDataStoreModule
    fullName: Cqrs.Ninject.MongoDB.Configuration.TestMongoDbDataStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
