### YamlMime:ManagedReference
items:
- uid: Cqrs.Configuration.HandlerDelegate
  commentId: T:Cqrs.Configuration.HandlerDelegate
  id: HandlerDelegate
  parent: Cqrs.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: HandlerDelegate
  nameWithType: HandlerDelegate
  fullName: Cqrs.Configuration.HandlerDelegate
  type: Class
  source:
    remote:
      path: Framework/Cqrs/Configuration/HandlerDelegate.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: HandlerDelegate
    path: Framework/Cqrs/Configuration/HandlerDelegate.cs
    startLine: 16
  assemblies:
  - Cqrs
  namespace: Cqrs.Configuration
  summary: "\nInformation about a <xref href=\"Cqrs.Messages.IHandler\" data-throw-if-not-resolved=\"false\"></xref> delegate.\n"
  example: []
  syntax:
    content: 'public class HandlerDelegate : HandlerDelegate<dynamic>'
    content.vb: >-
      Public Class HandlerDelegate

          Inherits HandlerDelegate(Of Object)
  inheritance:
  - System.Object
  - Cqrs.Configuration.HandlerDelegate{System.Object}
  inheritedMembers:
  - Cqrs.Configuration.HandlerDelegate{System.Object}.Delegate
  - Cqrs.Configuration.HandlerDelegate{System.Object}.TargetedType
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
references:
- uid: Cqrs.Messages.IHandler
  commentId: T:Cqrs.Messages.IHandler
  parent: Cqrs.Messages
  isExternal: false
  name: IHandler
  nameWithType: IHandler
  fullName: Cqrs.Messages.IHandler
- uid: Cqrs.Configuration
  commentId: N:Cqrs.Configuration
  isExternal: false
  name: Cqrs.Configuration
  nameWithType: Cqrs.Configuration
  fullName: Cqrs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Configuration.HandlerDelegate{System.Object}
  commentId: T:Cqrs.Configuration.HandlerDelegate{System.Object}
  parent: Cqrs.Configuration
  definition: Cqrs.Configuration.HandlerDelegate`1
  name: HandlerDelegate<Object>
  nameWithType: HandlerDelegate<Object>
  fullName: Cqrs.Configuration.HandlerDelegate<System.Object>
  nameWithType.vb: HandlerDelegate(Of )
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of )
  name.vb: HandlerDelegate(Of )
  spec.csharp:
  - uid: Cqrs.Configuration.HandlerDelegate`1
    name: HandlerDelegate
    nameWithType: HandlerDelegate
    fullName: Cqrs.Configuration.HandlerDelegate
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Configuration.HandlerDelegate`1
    name: HandlerDelegate
    nameWithType: HandlerDelegate
    fullName: Cqrs.Configuration.HandlerDelegate
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.HandlerDelegate{System.Object}.Delegate
  commentId: P:Cqrs.Configuration.HandlerDelegate{System.Object}.Delegate
  parent: Cqrs.Configuration.HandlerDelegate{System.Object}
  definition: Cqrs.Configuration.HandlerDelegate`1.Delegate
  name: Delegate
  nameWithType: HandlerDelegate<Object>.Delegate
  fullName: Cqrs.Configuration.HandlerDelegate<System.Object>.Delegate
  nameWithType.vb: HandlerDelegate(Of Object).Delegate
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of System.Object).Delegate
- uid: Cqrs.Configuration.HandlerDelegate{System.Object}.TargetedType
  commentId: P:Cqrs.Configuration.HandlerDelegate{System.Object}.TargetedType
  parent: Cqrs.Configuration.HandlerDelegate{System.Object}
  definition: Cqrs.Configuration.HandlerDelegate`1.TargetedType
  name: TargetedType
  nameWithType: HandlerDelegate<Object>.TargetedType
  fullName: Cqrs.Configuration.HandlerDelegate<System.Object>.TargetedType
  nameWithType.vb: HandlerDelegate(Of Object).TargetedType
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of System.Object).TargetedType
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Messages
  commentId: N:Cqrs.Messages
  isExternal: false
  name: Cqrs.Messages
  nameWithType: Cqrs.Messages
  fullName: Cqrs.Messages
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Configuration.HandlerDelegate`1
  commentId: T:Cqrs.Configuration.HandlerDelegate`1
  isExternal: false
  name: HandlerDelegate<T>
  nameWithType: HandlerDelegate<T>
  fullName: Cqrs.Configuration.HandlerDelegate<T>
  nameWithType.vb: HandlerDelegate(Of T)
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of T)
  name.vb: HandlerDelegate(Of T)
  spec.csharp:
  - uid: Cqrs.Configuration.HandlerDelegate`1
    name: HandlerDelegate
    nameWithType: HandlerDelegate
    fullName: Cqrs.Configuration.HandlerDelegate
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Configuration.HandlerDelegate`1
    name: HandlerDelegate
    nameWithType: HandlerDelegate
    fullName: Cqrs.Configuration.HandlerDelegate
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.HandlerDelegate`1.Delegate
  commentId: P:Cqrs.Configuration.HandlerDelegate`1.Delegate
  isExternal: false
  name: Delegate
  nameWithType: HandlerDelegate<T>.Delegate
  fullName: Cqrs.Configuration.HandlerDelegate<T>.Delegate
  nameWithType.vb: HandlerDelegate(Of T).Delegate
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of T).Delegate
- uid: Cqrs.Configuration.HandlerDelegate`1.TargetedType
  commentId: P:Cqrs.Configuration.HandlerDelegate`1.TargetedType
  isExternal: false
  name: TargetedType
  nameWithType: HandlerDelegate<T>.TargetedType
  fullName: Cqrs.Configuration.HandlerDelegate<T>.TargetedType
  nameWithType.vb: HandlerDelegate(Of T).TargetedType
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of T).TargetedType
