### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  commentId: T:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  id: SimplifiedNinjectWebApi
  parent: Cqrs.Ninject.WebApi.Configuration
  children:
  - Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
  - Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
  langs:
  - csharp
  - vb
  name: SimplifiedNinjectWebApi
  nameWithType: SimplifiedNinjectWebApi
  fullName: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  type: Class
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.WebApi/Configuration/SimplifiedNinjectWebApi.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: SimplifiedNinjectWebApi
    path: Framework/Ninject/Cqrs.Ninject.WebApi/Configuration/SimplifiedNinjectWebApi.cs
    startLine: 25
  assemblies:
  - Cqrs.Ninject.WebApi
  namespace: Cqrs.Ninject.WebApi.Configuration
  summary: "\nA <xref href=\"WebActivatorEx.PreApplicationStartMethodAttribute\" data-throw-if-not-resolved=\"false\"></xref> that calls <xref href=\"Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start\" data-throw-if-not-resolved=\"false\"></xref>\nand <xref href=\"WebActivatorEx.ApplicationShutdownMethodAttribute\" data-throw-if-not-resolved=\"false\"></xref> that calls <xref href=\"Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop\" data-throw-if-not-resolved=\"false\"></xref>\nconfiguring Simplified SQL by wiring up <xref href=\"Cqrs.Ninject.Configuration.SimplifiedSqlModule%601\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public static class SimplifiedNinjectWebApi
    content.vb: Public Module SimplifiedNinjectWebApi
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
  commentId: M:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
  id: Start
  parent: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  langs:
  - csharp
  - vb
  name: Start()
  nameWithType: SimplifiedNinjectWebApi.Start()
  fullName: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.WebApi/Configuration/SimplifiedNinjectWebApi.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Start
    path: Framework/Ninject/Cqrs.Ninject.WebApi/Configuration/SimplifiedNinjectWebApi.cs
    startLine: 32
  assemblies:
  - Cqrs.Ninject.WebApi
  namespace: Cqrs.Ninject.WebApi.Configuration
  summary: "\nStarts the application.\n"
  example: []
  syntax:
    content: public static void Start()
    content.vb: Public Shared Sub Start
  overload: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
  commentId: M:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
  id: Stop
  parent: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi
  langs:
  - csharp
  - vb
  name: Stop()
  nameWithType: SimplifiedNinjectWebApi.Stop()
  fullName: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.WebApi/Configuration/SimplifiedNinjectWebApi.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Stop
    path: Framework/Ninject/Cqrs.Ninject.WebApi/Configuration/SimplifiedNinjectWebApi.cs
    startLine: 42
  assemblies:
  - Cqrs.Ninject.WebApi
  namespace: Cqrs.Ninject.WebApi.Configuration
  summary: "\nStops the application.\n"
  example: []
  syntax:
    content: public static void Stop()
    content.vb: Public Shared Sub Stop
  overload: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: WebActivatorEx.PreApplicationStartMethodAttribute
  commentId: T:WebActivatorEx.PreApplicationStartMethodAttribute
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
  commentId: M:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
- uid: WebActivatorEx.ApplicationShutdownMethodAttribute
  commentId: T:WebActivatorEx.ApplicationShutdownMethodAttribute
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
  commentId: M:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
- uid: Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
  commentId: T:Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
  isExternal: false
  name: SimplifiedSqlModule<TAuthenticationToken>
  nameWithType: SimplifiedSqlModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Configuration.SimplifiedSqlModule<TAuthenticationToken>
  nameWithType.vb: SimplifiedSqlModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Configuration.SimplifiedSqlModule(Of TAuthenticationToken)
  name.vb: SimplifiedSqlModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
    name: SimplifiedSqlModule
    nameWithType: SimplifiedSqlModule
    fullName: Cqrs.Ninject.Configuration.SimplifiedSqlModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.SimplifiedSqlModule`1
    name: SimplifiedSqlModule
    nameWithType: SimplifiedSqlModule
    fullName: Cqrs.Ninject.Configuration.SimplifiedSqlModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.WebApi.Configuration
  commentId: N:Cqrs.Ninject.WebApi.Configuration
  isExternal: false
  name: Cqrs.Ninject.WebApi.Configuration
  nameWithType: Cqrs.Ninject.WebApi.Configuration
  fullName: Cqrs.Ninject.WebApi.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start*
  commentId: Overload:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
  isExternal: false
  name: Start
  nameWithType: SimplifiedNinjectWebApi.Start
  fullName: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Start
- uid: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop*
  commentId: Overload:Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
  isExternal: false
  name: Stop
  nameWithType: SimplifiedNinjectWebApi.Stop
  fullName: Cqrs.Ninject.WebApi.Configuration.SimplifiedNinjectWebApi.Stop
