### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.WebJobs.Configuration
  commentId: N:Cqrs.Ninject.Azure.WebJobs.Configuration
  id: Cqrs.Ninject.Azure.WebJobs.Configuration
  children:
  - Cqrs.Ninject.Azure.WebJobs.Configuration.WebJobHostModule
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Azure.WebJobs.Configuration
  nameWithType: Cqrs.Ninject.Azure.WebJobs.Configuration
  fullName: Cqrs.Ninject.Azure.WebJobs.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Azure.WebJobs
references:
- uid: Cqrs.Ninject.Azure.WebJobs.Configuration.WebJobHostModule
  commentId: T:Cqrs.Ninject.Azure.WebJobs.Configuration.WebJobHostModule
  isExternal: false
  name: WebJobHostModule
  nameWithType: WebJobHostModule
  fullName: Cqrs.Ninject.Azure.WebJobs.Configuration.WebJobHostModule
