### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.Wcf.Configuration
  commentId: N:Cqrs.Ninject.Azure.Wcf.Configuration
  id: Cqrs.Ninject.Azure.Wcf.Configuration
  children:
  - Cqrs.Ninject.Azure.Wcf.Configuration.SimplifiedNinjectWcf
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Azure.Wcf.Configuration
  nameWithType: Cqrs.Ninject.Azure.Wcf.Configuration
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
references:
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.SimplifiedNinjectWcf
  commentId: T:Cqrs.Ninject.Azure.Wcf.Configuration.SimplifiedNinjectWcf
  isExternal: false
  name: SimplifiedNinjectWcf
  nameWithType: SimplifiedNinjectWcf
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.SimplifiedNinjectWcf
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  commentId: T:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  parent: Cqrs.Ninject.Azure.Wcf.Configuration
  isExternal: false
  name: WebHostModule
  nameWithType: WebHostModule
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
- uid: Cqrs.Ninject.Azure.Wcf.Configuration
  commentId: N:Cqrs.Ninject.Azure.Wcf.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.Wcf.Configuration
  nameWithType: Cqrs.Ninject.Azure.Wcf.Configuration
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration
