### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  id: AzureEventHubReceiverModule`1
  parent: Cqrs.Azure.EventHub.EventBus.Configuration
  children:
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  langs:
  - csharp
  - vb
  name: AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureEventHubReceiverModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
    startLine: 21
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
  namespace: Cqrs.Azure.EventHub.EventBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureEventBusReceiver%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Events.IEventReceiver\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureEventHubReceiverModule<TAuthenticationToken> : NinjectModule'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureEventHubReceiverModule(Of TAuthenticationToken)

          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule`1
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  id: Load
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
    startLine: 28
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
  namespace: Cqrs.Azure.EventHub.EventBus.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load*
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).Load()
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).Load()
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  id: RegisterEventHandlerRegistrar
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: RegisterEventHandlerRegistrar()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterEventHandlerRegistrar
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
    startLine: 47
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
  namespace: Cqrs.Azure.EventHub.EventBus.Configuration
  summary: "\nRegister the CQRS event handler registrar\n"
  example: []
  syntax:
    content: public virtual void RegisterEventHandlerRegistrar()
    content.vb: Public Overridable Sub RegisterEventHandlerRegistrar
  overload: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar*
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar()
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  id: RegisterEventMessageSerialiser
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: RegisterEventMessageSerialiser()
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterEventMessageSerialiser
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventHubReceiverModule.cs
    startLine: 57
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
  namespace: Cqrs.Azure.EventHub.EventBus.Configuration
  summary: "\nRegister the CQRS event handler message serialiser\n"
  example: []
  syntax:
    content: public virtual void RegisterEventMessageSerialiser()
    content.vb: Public Overridable Sub RegisterEventMessageSerialiser
  overload: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser*
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
references:
- uid: Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
  isExternal: false
  name: AzureEventBusReceiver<TAuthenticationToken>
  nameWithType: AzureEventBusReceiver<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureEventBusReceiver<TAuthenticationToken>
  nameWithType.vb: AzureEventBusReceiver(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureEventBusReceiver(Of TAuthenticationToken)
  name.vb: AzureEventBusReceiver(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
    name: AzureEventBusReceiver
    nameWithType: AzureEventBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusReceiver
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusReceiver`1
    name: AzureEventBusReceiver
    nameWithType: AzureEventBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusReceiver
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Events.IEventReceiver
  commentId: T:Cqrs.Events.IEventReceiver
  parent: Cqrs.Events
  isExternal: false
  name: IEventReceiver
  nameWithType: IEventReceiver
  fullName: Cqrs.Events.IEventReceiver
- uid: Cqrs.Azure.EventHub.EventBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.EventBus.Configuration
  isExternal: false
  name: Cqrs.Azure.EventHub.EventBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.EventBus.Configuration
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Events
  commentId: N:Cqrs.Events
  isExternal: false
  name: Cqrs.Events
  nameWithType: Cqrs.Events
  fullName: Cqrs.Events
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load*
  commentId: Overload:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.Load
  isExternal: false
  name: Load
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.Load
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.Load
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).Load
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).Load
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar*
  commentId: Overload:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventHandlerRegistrar
  isExternal: false
  name: RegisterEventHandlerRegistrar
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventHandlerRegistrar
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventHandlerRegistrar
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser*
  commentId: Overload:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1.RegisterEventMessageSerialiser
  isExternal: false
  name: RegisterEventMessageSerialiser
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
