### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  commentId: T:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  id: WebHostModule
  parent: Cqrs.Ninject.Azure.Wcf.Configuration
  children:
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory
  - Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit
  langs:
  - csharp
  - vb
  name: WebHostModule
  nameWithType: WebHostModule
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: WebHostModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 30
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nThe core <xref href=\"Ninject.Modules.INinjectModule\" data-throw-if-not-resolved=\"false\"></xref> for use defining base level requirements.\n"
  example: []
  syntax:
    content: 'public class WebHostModule : ResolvableModule'
    content.vb: >-
      Public Class WebHostModule
          Inherits ResolvableModule
  inheritance:
  - System.Object
  - Cqrs.Ninject.Configuration.ResolvableModule
  derivedClasses:
  - Cqrs.Ninject.Azure.WebJobs.Configuration.WebJobHostModule
  inheritedMembers:
  - Cqrs.Ninject.Configuration.ResolvableModule.Resolve``1
  - Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Type)
  - Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered``1
  - Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Type)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load
  commentId: M:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load
  id: Load
  parent: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: WebHostModule.Load()
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 37
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations
  commentId: M:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations
  id: RegisterAzureConfigurations
  parent: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: RegisterAzureConfigurations()
  nameWithType: WebHostModule.RegisterAzureConfigurations()
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterAzureConfigurations
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 50
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nRegister the all Azure configurations\n"
  example: []
  syntax:
    content: protected virtual void RegisterAzureConfigurations()
    content.vb: Protected Overridable Sub RegisterAzureConfigurations
  overload: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations*
  modifiers.csharp:
  - protected
  - virtual
  modifiers.vb:
  - Protected
  - Overridable
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers
  commentId: M:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers
  id: RegisterBasicHelpers
  parent: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: RegisterBasicHelpers()
  nameWithType: WebHostModule.RegisterBasicHelpers()
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterBasicHelpers
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 64
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nRegisters the basic helpers required.\n"
  example: []
  syntax:
    content: protected virtual void RegisterBasicHelpers()
    content.vb: Protected Overridable Sub RegisterBasicHelpers
  overload: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers*
  modifiers.csharp:
  - protected
  - virtual
  modifiers.vb:
  - Protected
  - Overridable
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory
  commentId: M:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory
  id: RegisterContextItemCollectionFactory
  parent: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: RegisterContextItemCollectionFactory()
  nameWithType: WebHostModule.RegisterContextItemCollectionFactory()
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterContextItemCollectionFactory
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 75
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nRegisters the <xref href=\"cdmdotnet.StateManagement.IContextItemCollectionFactory\" data-throw-if-not-resolved=\"false\"></xref> required.\n"
  example: []
  syntax:
    content: protected virtual void RegisterContextItemCollectionFactory()
    content.vb: Protected Overridable Sub RegisterContextItemCollectionFactory
  overload: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory*
  modifiers.csharp:
  - protected
  - virtual
  modifiers.vb:
  - Protected
  - Overridable
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives
  commentId: M:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives
  id: RegisterBasicSerives
  parent: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: RegisterBasicSerives()
  nameWithType: WebHostModule.RegisterBasicSerives()
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterBasicSerives
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 86
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nRegisters the basic services required.\n"
  example: []
  syntax:
    content: protected virtual void RegisterBasicSerives()
    content.vb: Protected Overridable Sub RegisterBasicSerives
  overload: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives*
  modifiers.csharp:
  - protected
  - virtual
  modifiers.vb:
  - Protected
  - Overridable
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit
  commentId: M:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit
  id: RegisterWebBit
  parent: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule
  langs:
  - csharp
  - vb
  name: RegisterWebBit()
  nameWithType: WebHostModule.RegisterWebBit()
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterWebBit
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.Wcf/Configuration/WebHostModule.cs
    startLine: 143
  assemblies:
  - Cqrs.Ninject.Azure.Wcf
  namespace: Cqrs.Ninject.Azure.Wcf.Configuration
  summary: "\nRegisters some things Ninject likes.\n"
  example: []
  syntax:
    content: protected virtual void RegisterWebBit()
    content.vb: Protected Overridable Sub RegisterWebBit
  overload: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit*
  modifiers.csharp:
  - protected
  - virtual
  modifiers.vb:
  - Protected
  - Overridable
references:
- uid: Ninject.Modules.INinjectModule
  commentId: T:Ninject.Modules.INinjectModule
  parent: Ninject.Modules
  isExternal: true
  name: INinjectModule
  nameWithType: INinjectModule
  fullName: Ninject.Modules.INinjectModule
- uid: Cqrs.Ninject.Azure.Wcf.Configuration
  commentId: N:Cqrs.Ninject.Azure.Wcf.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.Wcf.Configuration
  nameWithType: Cqrs.Ninject.Azure.Wcf.Configuration
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Ninject.Configuration.ResolvableModule
  commentId: T:Cqrs.Ninject.Configuration.ResolvableModule
  parent: Cqrs.Ninject.Configuration
  isExternal: false
  name: ResolvableModule
  nameWithType: ResolvableModule
  fullName: Cqrs.Ninject.Configuration.ResolvableModule
- uid: Cqrs.Ninject.Configuration.ResolvableModule.Resolve``1
  commentId: M:Cqrs.Ninject.Configuration.ResolvableModule.Resolve``1
  parent: Cqrs.Ninject.Configuration.ResolvableModule
  isExternal: false
  name: Resolve<T>()
  nameWithType: ResolvableModule.Resolve<T>()
  fullName: Cqrs.Ninject.Configuration.ResolvableModule.Resolve<T>()
  nameWithType.vb: ResolvableModule.Resolve(Of T)()
  fullName.vb: Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Of T)()
  name.vb: Resolve(Of T)()
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.Resolve``1
    name: Resolve<T>
    nameWithType: ResolvableModule.Resolve<T>
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.Resolve<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.Resolve``1
    name: Resolve(Of T)
    nameWithType: ResolvableModule.Resolve(Of T)
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Type)
  commentId: M:Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Type)
  parent: Cqrs.Ninject.Configuration.ResolvableModule
  isExternal: true
  name: Resolve(Type)
  nameWithType: ResolvableModule.Resolve(Type)
  fullName: Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Type)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Type)
    name: Resolve
    nameWithType: ResolvableModule.Resolve
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.Resolve
  - name: (
    nameWithType: (
    fullName: (
  - uid: Type
    name: Type
    nameWithType: Type
    fullName: Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.Resolve(Type)
    name: Resolve
    nameWithType: ResolvableModule.Resolve
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.Resolve
  - name: (
    nameWithType: (
    fullName: (
  - uid: Type
    name: Type
    nameWithType: Type
    fullName: Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered``1
  commentId: M:Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered``1
  parent: Cqrs.Ninject.Configuration.ResolvableModule
  isExternal: false
  name: IsRegistered<T>()
  nameWithType: ResolvableModule.IsRegistered<T>()
  fullName: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered<T>()
  nameWithType.vb: ResolvableModule.IsRegistered(Of T)()
  fullName.vb: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Of T)()
  name.vb: IsRegistered(Of T)()
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered``1
    name: IsRegistered<T>
    nameWithType: ResolvableModule.IsRegistered<T>
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered``1
    name: IsRegistered(Of T)
    nameWithType: ResolvableModule.IsRegistered(Of T)
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Type)
  commentId: M:Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Type)
  parent: Cqrs.Ninject.Configuration.ResolvableModule
  isExternal: true
  name: IsRegistered(Type)
  nameWithType: ResolvableModule.IsRegistered(Type)
  fullName: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Type)
  spec.csharp:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Type)
    name: IsRegistered
    nameWithType: ResolvableModule.IsRegistered
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered
  - name: (
    nameWithType: (
    fullName: (
  - uid: Type
    name: Type
    nameWithType: Type
    fullName: Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered(Type)
    name: IsRegistered
    nameWithType: ResolvableModule.IsRegistered
    fullName: Cqrs.Ninject.Configuration.ResolvableModule.IsRegistered
  - name: (
    nameWithType: (
    fullName: (
  - uid: Type
    name: Type
    nameWithType: Type
    fullName: Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Ninject.Modules
  commentId: N:Ninject.Modules
  isExternal: false
  name: Ninject.Modules
  nameWithType: Ninject.Modules
  fullName: Ninject.Modules
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Configuration
  commentId: N:Cqrs.Ninject.Configuration
  isExternal: false
  name: Cqrs.Ninject.Configuration
  nameWithType: Cqrs.Ninject.Configuration
  fullName: Cqrs.Ninject.Configuration
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load*
  commentId: Overload:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load
  isExternal: false
  name: Load
  nameWithType: WebHostModule.Load
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.Load
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations*
  commentId: Overload:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations
  isExternal: false
  name: RegisterAzureConfigurations
  nameWithType: WebHostModule.RegisterAzureConfigurations
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterAzureConfigurations
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers*
  commentId: Overload:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers
  isExternal: false
  name: RegisterBasicHelpers
  nameWithType: WebHostModule.RegisterBasicHelpers
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicHelpers
- uid: cdmdotnet.StateManagement.IContextItemCollectionFactory
  commentId: T:cdmdotnet.StateManagement.IContextItemCollectionFactory
  parent: cdmdotnet.StateManagement
  isExternal: true
  name: IContextItemCollectionFactory
  nameWithType: IContextItemCollectionFactory
  fullName: cdmdotnet.StateManagement.IContextItemCollectionFactory
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory*
  commentId: Overload:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory
  isExternal: false
  name: RegisterContextItemCollectionFactory
  nameWithType: WebHostModule.RegisterContextItemCollectionFactory
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterContextItemCollectionFactory
- uid: cdmdotnet.StateManagement
  commentId: N:cdmdotnet.StateManagement
  isExternal: false
  name: cdmdotnet.StateManagement
  nameWithType: cdmdotnet.StateManagement
  fullName: cdmdotnet.StateManagement
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives*
  commentId: Overload:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives
  isExternal: false
  name: RegisterBasicSerives
  nameWithType: WebHostModule.RegisterBasicSerives
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterBasicSerives
- uid: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit*
  commentId: Overload:Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit
  isExternal: false
  name: RegisterWebBit
  nameWithType: WebHostModule.RegisterWebBit
  fullName: Cqrs.Ninject.Azure.Wcf.Configuration.WebHostModule.RegisterWebBit
