### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.CommandBus.Configuration
  id: Cqrs.Azure.EventHub.CommandBus.Configuration
  children:
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Azure.EventHub.CommandBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.CommandBus.Configuration
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
references:
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  isExternal: false
  name: AzureCommandHubPublisherModule<TAuthenticationToken>
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken)
  name.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
    name: AzureCommandHubPublisherModule
    nameWithType: AzureCommandHubPublisherModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
    name: AzureCommandHubPublisherModule
    nameWithType: AzureCommandHubPublisherModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  isExternal: false
  name: AzureCommandBusPublisherModule<TAuthenticationToken>
  nameWithType: AzureCommandBusPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule`1
    name: AzureCommandBusPublisherModule
    nameWithType: AzureCommandBusPublisherModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule`1
    name: AzureCommandBusPublisherModule
    nameWithType: AzureCommandBusPublisherModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  isExternal: false
  name: AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
    name: AzureCommandHubReceiverModule
    nameWithType: AzureCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
    name: AzureCommandHubReceiverModule
    nameWithType: AzureCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule`1
  isExternal: false
  name: AzureCommandBusSenderModule<TAuthenticationToken>
  nameWithType: AzureCommandBusSenderModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusSenderModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusSenderModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule`1
    name: AzureCommandBusSenderModule
    nameWithType: AzureCommandBusSenderModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule`1
    name: AzureCommandBusSenderModule
    nameWithType: AzureCommandBusSenderModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  isExternal: false
  name: AzureCommandBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
    name: AzureCommandBusReceiverModule
    nameWithType: AzureCommandBusReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
    name: AzureCommandBusReceiverModule
    nameWithType: AzureCommandBusReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule`1
  isExternal: false
  name: AzureQueuedCommandHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureQueuedCommandHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureQueuedCommandHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureQueuedCommandHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule`1
    name: AzureQueuedCommandHubReceiverModule
    nameWithType: AzureQueuedCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule`1
    name: AzureQueuedCommandHubReceiverModule
    nameWithType: AzureQueuedCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
  isExternal: false
  name: AzureQueuedCommandBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureQueuedCommandBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureQueuedCommandBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureQueuedCommandBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
    name: AzureQueuedCommandBusReceiverModule
    nameWithType: AzureQueuedCommandBusReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
    name: AzureQueuedCommandBusReceiverModule
    nameWithType: AzureQueuedCommandBusReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
