### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.InProcess.EventStore.Configuration
  commentId: N:Cqrs.Ninject.InProcess.EventStore.Configuration
  id: Cqrs.Ninject.InProcess.EventStore.Configuration
  children:
  - Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.InProcess.EventStore.Configuration
  nameWithType: Cqrs.Ninject.InProcess.EventStore.Configuration
  fullName: Cqrs.Ninject.InProcess.EventStore.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.InProcess.EventStore
references:
- uid: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule`1
  commentId: T:Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule`1
  isExternal: false
  name: InProcessEventStoreModule<TAuthenticationToken>
  nameWithType: InProcessEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule<TAuthenticationToken>
  nameWithType.vb: InProcessEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule(Of TAuthenticationToken)
  name.vb: InProcessEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule`1
    name: InProcessEventStoreModule
    nameWithType: InProcessEventStoreModule
    fullName: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule`1
    name: InProcessEventStoreModule
    nameWithType: InProcessEventStoreModule
    fullName: Cqrs.Ninject.InProcess.EventStore.Configuration.InProcessEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
