### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  id: AzureDocumentDbModule
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration
  children:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  langs:
  - csharp
  - vb
  name: AzureDocumentDbModule
  nameWithType: AzureDocumentDbModule
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureDocumentDbModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
    startLine: 18
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.DocumentDb.Factories.AzureDocumentDbDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class AzureDocumentDbModule : NinjectModule'
    content.vb: >-
      Public Class AzureDocumentDbModule
          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  id: Load
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: AzureDocumentDbModule.Load()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
    startLine: 25
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  id: RegisterFactories
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: RegisterFactories()
  nameWithType: AzureDocumentDbModule.RegisterFactories()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterFactories
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
    startLine: 38
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister the all factories\n"
  example: []
  syntax:
    content: public virtual void RegisterFactories()
    content.vb: Public Overridable Sub RegisterFactories
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  id: RegisterServices
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: RegisterServices()
  nameWithType: AzureDocumentDbModule.RegisterServices()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterServices
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
    startLine: 48
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister the all services\n"
  example: []
  syntax:
    content: public virtual void RegisterServices()
    content.vb: Public Overridable Sub RegisterServices
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  id: RegisterCqrsRequirements
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: RegisterCqrsRequirements()
  nameWithType: AzureDocumentDbModule.RegisterCqrsRequirements()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterCqrsRequirements
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
    startLine: 55
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister any CQRS requirements.\n"
  example: []
  syntax:
    content: public virtual void RegisterCqrsRequirements()
    content.vb: Public Overridable Sub RegisterCqrsRequirements
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  id: RegisterAzureHelpers
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: RegisterAzureHelpers()
  nameWithType: AzureDocumentDbModule.RegisterAzureHelpers()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterAzureHelpers
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbModule.cs
    startLine: 62
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister <xref href=\"Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper\" data-throw-if-not-resolved=\"false\"></xref> if it hasn&apos;t already been registered.\n"
  example: []
  syntax:
    content: public virtual void RegisterAzureHelpers()
    content.vb: Public Overridable Sub RegisterAzureHelpers
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Cqrs.Azure.DocumentDb.Factories.AzureDocumentDbDataStoreConnectionStringFactory
  commentId: T:Cqrs.Azure.DocumentDb.Factories.AzureDocumentDbDataStoreConnectionStringFactory
  parent: Cqrs.Azure.DocumentDb.Factories
  isExternal: false
  name: AzureDocumentDbDataStoreConnectionStringFactory
  nameWithType: AzureDocumentDbDataStoreConnectionStringFactory
  fullName: Cqrs.Azure.DocumentDb.Factories.AzureDocumentDbDataStoreConnectionStringFactory
- uid: Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory
  commentId: T:Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory
  parent: Cqrs.Azure.DocumentDb.Factories
  isExternal: false
  name: IAzureDocumentDbDataStoreConnectionStringFactory
  nameWithType: IAzureDocumentDbDataStoreConnectionStringFactory
  fullName: Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration
  commentId: N:Cqrs.Ninject.Azure.DocumentDb.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.DocumentDb.Configuration
  nameWithType: Cqrs.Ninject.Azure.DocumentDb.Configuration
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Azure.DocumentDb.Factories
  commentId: N:Cqrs.Azure.DocumentDb.Factories
  isExternal: false
  name: Cqrs.Azure.DocumentDb.Factories
  nameWithType: Cqrs.Azure.DocumentDb.Factories
  fullName: Cqrs.Azure.DocumentDb.Factories
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  isExternal: false
  name: Load
  nameWithType: AzureDocumentDbModule.Load
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  isExternal: false
  name: RegisterFactories
  nameWithType: AzureDocumentDbModule.RegisterFactories
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  isExternal: false
  name: RegisterServices
  nameWithType: AzureDocumentDbModule.RegisterServices
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  isExternal: false
  name: RegisterCqrsRequirements
  nameWithType: AzureDocumentDbModule.RegisterCqrsRequirements
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
- uid: Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper
  commentId: T:Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper
  parent: Cqrs.Azure.DocumentDb
  isExternal: false
  name: IAzureDocumentDbHelper
  nameWithType: IAzureDocumentDbHelper
  fullName: Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  isExternal: false
  name: RegisterAzureHelpers
  nameWithType: AzureDocumentDbModule.RegisterAzureHelpers
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
- uid: Cqrs.Azure.DocumentDb
  commentId: N:Cqrs.Azure.DocumentDb
  isExternal: false
  name: Cqrs.Azure.DocumentDb
  nameWithType: Cqrs.Azure.DocumentDb
  fullName: Cqrs.Azure.DocumentDb
