### YamlMime:ManagedReference
items:
- uid: Cqrs.Configuration.IConfigurationManager
  commentId: T:Cqrs.Configuration.IConfigurationManager
  id: IConfigurationManager
  parent: Cqrs.Configuration
  children:
  - Cqrs.Configuration.IConfigurationManager.GetSetting(System.String)
  - Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String,System.Boolean@)
  - Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String,System.String@)
  langs:
  - csharp
  - vb
  name: IConfigurationManager
  nameWithType: IConfigurationManager
  fullName: Cqrs.Configuration.IConfigurationManager
  type: Interface
  source:
    remote:
      path: Framework/Cqrs/Configuration/IConfigurationManager.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: IConfigurationManager
    path: Framework/Cqrs/Configuration/IConfigurationManager.cs
    startLine: 13
  assemblies:
  - Cqrs
  namespace: Cqrs.Configuration
  summary: "\nProvides access to configuration settings.\n"
  example: []
  syntax:
    content: public interface IConfigurationManager
    content.vb: Public Interface IConfigurationManager
  extensionMethods:
  - Cqrs.Configuration.IConfigurationManager.Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,Cqrs.Configuration.IDependencyResolver)
  - Cqrs.Configuration.IConfigurationManager.Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,cdmdotnet.Logging.ICorrelationIdHelper)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Cqrs.Configuration.IConfigurationManager.GetSetting(System.String)
  commentId: M:Cqrs.Configuration.IConfigurationManager.GetSetting(System.String)
  id: GetSetting(System.String)
  parent: Cqrs.Configuration.IConfigurationManager
  langs:
  - csharp
  - vb
  name: GetSetting(String)
  nameWithType: IConfigurationManager.GetSetting(String)
  fullName: Cqrs.Configuration.IConfigurationManager.GetSetting(System.String)
  type: Method
  source:
    remote:
      path: Framework/Cqrs/Configuration/IConfigurationManager.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: GetSetting
    path: Framework/Cqrs/Configuration/IConfigurationManager.cs
    startLine: 19
  assemblies:
  - Cqrs
  namespace: Cqrs.Configuration
  summary: "\nRead the setting named <code data-dev-comment-type=\"paramref\">key</code>.\n"
  example: []
  syntax:
    content: string GetSetting(string key)
    parameters:
    - id: key
      type: System.String
      description: The key (or name) of the setting to read.
    return:
      type: System.String
    content.vb: Function GetSetting(key As String) As String
  overload: Cqrs.Configuration.IConfigurationManager.GetSetting*
- uid: Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String,System.String@)
  commentId: M:Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String,System.String@)
  id: TryGetSetting(System.String,System.String@)
  parent: Cqrs.Configuration.IConfigurationManager
  langs:
  - csharp
  - vb
  name: TryGetSetting(String, out String)
  nameWithType: IConfigurationManager.TryGetSetting(String, out String)
  fullName: Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String, out System.String)
  type: Method
  source:
    remote:
      path: Framework/Cqrs/Configuration/IConfigurationManager.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: TryGetSetting
    path: Framework/Cqrs/Configuration/IConfigurationManager.cs
    startLine: 27
  assemblies:
  - Cqrs
  namespace: Cqrs.Configuration
  summary: "\nRead the setting named <code data-dev-comment-type=\"paramref\">key</code>.\n"
  example: []
  syntax:
    content: bool TryGetSetting(string key, out string value)
    parameters:
    - id: key
      type: System.String
      description: The key (or name) of the setting to read.
    - id: value
      type: System.String
      description: When this method returns, the value associated with the specified key, if the key is found; otherwise, the default value for the type of the value parameter. This parameter is passed uninitialized.
    return:
      type: System.Boolean
      description: true if the an element with the specified key exists; otherwise, false.
    content.vb: Function TryGetSetting(key As String, ByRef value As String) As Boolean
  overload: Cqrs.Configuration.IConfigurationManager.TryGetSetting*
  nameWithType.vb: IConfigurationManager.TryGetSetting(String, ByRef String)
  fullName.vb: Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String, ByRef System.String)
  name.vb: TryGetSetting(String, ByRef String)
- uid: Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String,System.Boolean@)
  commentId: M:Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String,System.Boolean@)
  id: TryGetSetting(System.String,System.Boolean@)
  parent: Cqrs.Configuration.IConfigurationManager
  langs:
  - csharp
  - vb
  name: TryGetSetting(String, out Boolean)
  nameWithType: IConfigurationManager.TryGetSetting(String, out Boolean)
  fullName: Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String, out System.Boolean)
  type: Method
  source:
    remote:
      path: Framework/Cqrs/Configuration/IConfigurationManager.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: TryGetSetting
    path: Framework/Cqrs/Configuration/IConfigurationManager.cs
    startLine: 35
  assemblies:
  - Cqrs
  namespace: Cqrs.Configuration
  summary: "\nRead the setting named <code data-dev-comment-type=\"paramref\">key</code>.\n"
  example: []
  syntax:
    content: bool TryGetSetting(string key, out bool value)
    parameters:
    - id: key
      type: System.String
      description: The key (or name) of the setting to read.
    - id: value
      type: System.Boolean
      description: When this method returns, the value associated with the specified key, if the key is found; otherwise, the default value for the type of the value parameter. This parameter is passed uninitialized.
    return:
      type: System.Boolean
      description: true if the an element with the specified key exists; otherwise, false.
    content.vb: Function TryGetSetting(key As String, ByRef value As Boolean) As Boolean
  overload: Cqrs.Configuration.IConfigurationManager.TryGetSetting*
  nameWithType.vb: IConfigurationManager.TryGetSetting(String, ByRef Boolean)
  fullName.vb: Cqrs.Configuration.IConfigurationManager.TryGetSetting(System.String, ByRef System.Boolean)
  name.vb: TryGetSetting(String, ByRef Boolean)
references:
- uid: Cqrs.Configuration
  commentId: N:Cqrs.Configuration
  isExternal: false
  name: Cqrs.Configuration
  nameWithType: Cqrs.Configuration
  fullName: Cqrs.Configuration
- uid: Cqrs.Configuration.IConfigurationManager.Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,Cqrs.Configuration.IDependencyResolver)
  commentId: M:Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,Cqrs.Configuration.IDependencyResolver)
  parent: Cqrs.Configuration.ConfigurationExtensions
  definition: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,Cqrs.Configuration.IDependencyResolver)
  name: CreateTelemetryHelper(String, IDependencyResolver)
  nameWithType: ConfigurationExtensions.CreateTelemetryHelper(String, IDependencyResolver)
  fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String, Cqrs.Configuration.IDependencyResolver)
  spec.csharp:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,Cqrs.Configuration.IDependencyResolver)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Cqrs.Configuration.IDependencyResolver
    name: IDependencyResolver
    nameWithType: IDependencyResolver
    fullName: Cqrs.Configuration.IDependencyResolver
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,Cqrs.Configuration.IDependencyResolver)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Cqrs.Configuration.IDependencyResolver
    name: IDependencyResolver
    nameWithType: IDependencyResolver
    fullName: Cqrs.Configuration.IDependencyResolver
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.IConfigurationManager.Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,cdmdotnet.Logging.ICorrelationIdHelper)
  commentId: M:Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,cdmdotnet.Logging.ICorrelationIdHelper)
  parent: Cqrs.Configuration.ConfigurationExtensions
  definition: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,cdmdotnet.Logging.ICorrelationIdHelper)
  name: CreateTelemetryHelper(String, ICorrelationIdHelper)
  nameWithType: ConfigurationExtensions.CreateTelemetryHelper(String, ICorrelationIdHelper)
  fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String, cdmdotnet.Logging.ICorrelationIdHelper)
  spec.csharp:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,cdmdotnet.Logging.ICorrelationIdHelper)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: cdmdotnet.Logging.ICorrelationIdHelper
    name: ICorrelationIdHelper
    nameWithType: ICorrelationIdHelper
    fullName: cdmdotnet.Logging.ICorrelationIdHelper
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(System.String,cdmdotnet.Logging.ICorrelationIdHelper)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: cdmdotnet.Logging.ICorrelationIdHelper
    name: ICorrelationIdHelper
    nameWithType: ICorrelationIdHelper
    fullName: cdmdotnet.Logging.ICorrelationIdHelper
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,Cqrs.Configuration.IDependencyResolver)
  commentId: M:Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,Cqrs.Configuration.IDependencyResolver)
  isExternal: true
  name: CreateTelemetryHelper(IConfigurationManager, String, IDependencyResolver)
  nameWithType: ConfigurationExtensions.CreateTelemetryHelper(IConfigurationManager, String, IDependencyResolver)
  fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager, System.String, Cqrs.Configuration.IDependencyResolver)
  spec.csharp:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,Cqrs.Configuration.IDependencyResolver)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: Cqrs.Configuration.IConfigurationManager
    name: IConfigurationManager
    nameWithType: IConfigurationManager
    fullName: Cqrs.Configuration.IConfigurationManager
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Cqrs.Configuration.IDependencyResolver
    name: IDependencyResolver
    nameWithType: IDependencyResolver
    fullName: Cqrs.Configuration.IDependencyResolver
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,Cqrs.Configuration.IDependencyResolver)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: Cqrs.Configuration.IConfigurationManager
    name: IConfigurationManager
    nameWithType: IConfigurationManager
    fullName: Cqrs.Configuration.IConfigurationManager
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Cqrs.Configuration.IDependencyResolver
    name: IDependencyResolver
    nameWithType: IDependencyResolver
    fullName: Cqrs.Configuration.IDependencyResolver
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.ConfigurationExtensions
  commentId: T:Cqrs.Configuration.ConfigurationExtensions
  parent: Cqrs.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Cqrs.Configuration.ConfigurationExtensions
- uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,cdmdotnet.Logging.ICorrelationIdHelper)
  commentId: M:Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,cdmdotnet.Logging.ICorrelationIdHelper)
  isExternal: true
  name: CreateTelemetryHelper(IConfigurationManager, String, ICorrelationIdHelper)
  nameWithType: ConfigurationExtensions.CreateTelemetryHelper(IConfigurationManager, String, ICorrelationIdHelper)
  fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager, System.String, cdmdotnet.Logging.ICorrelationIdHelper)
  spec.csharp:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,cdmdotnet.Logging.ICorrelationIdHelper)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: Cqrs.Configuration.IConfigurationManager
    name: IConfigurationManager
    nameWithType: IConfigurationManager
    fullName: Cqrs.Configuration.IConfigurationManager
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: cdmdotnet.Logging.ICorrelationIdHelper
    name: ICorrelationIdHelper
    nameWithType: ICorrelationIdHelper
    fullName: cdmdotnet.Logging.ICorrelationIdHelper
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper(Cqrs.Configuration.IConfigurationManager,System.String,cdmdotnet.Logging.ICorrelationIdHelper)
    name: CreateTelemetryHelper
    nameWithType: ConfigurationExtensions.CreateTelemetryHelper
    fullName: Cqrs.Configuration.ConfigurationExtensions.CreateTelemetryHelper
  - name: (
    nameWithType: (
    fullName: (
  - uid: Cqrs.Configuration.IConfigurationManager
    name: IConfigurationManager
    nameWithType: IConfigurationManager
    fullName: Cqrs.Configuration.IConfigurationManager
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: cdmdotnet.Logging.ICorrelationIdHelper
    name: ICorrelationIdHelper
    nameWithType: ICorrelationIdHelper
    fullName: cdmdotnet.Logging.ICorrelationIdHelper
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.IConfigurationManager.GetSetting*
  commentId: Overload:Cqrs.Configuration.IConfigurationManager.GetSetting
  isExternal: false
  name: GetSetting
  nameWithType: IConfigurationManager.GetSetting
  fullName: Cqrs.Configuration.IConfigurationManager.GetSetting
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Configuration.IConfigurationManager.TryGetSetting*
  commentId: Overload:Cqrs.Configuration.IConfigurationManager.TryGetSetting
  isExternal: false
  name: TryGetSetting
  nameWithType: IConfigurationManager.TryGetSetting
  fullName: Cqrs.Configuration.IConfigurationManager.TryGetSetting
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
