### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.BlobStorage.Configuration
  commentId: N:Cqrs.Ninject.Azure.BlobStorage.Configuration
  id: Cqrs.Ninject.Azure.BlobStorage.Configuration
  children:
  - Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStorageDataStoreModule
  - Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule`1
  - Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStorageDataStoreModule
  - Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Azure.BlobStorage.Configuration
  nameWithType: Cqrs.Ninject.Azure.BlobStorage.Configuration
  fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Azure.BlobStorage
references:
- uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStorageDataStoreModule
  commentId: T:Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStorageDataStoreModule
  isExternal: false
  name: BlobStorageDataStoreModule
  nameWithType: BlobStorageDataStoreModule
  fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStorageDataStoreModule
- uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule`1
  commentId: T:Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule`1
  isExternal: false
  name: BlobStoragEventStoreModule<TAuthenticationToken>
  nameWithType: BlobStoragEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule<TAuthenticationToken>
  nameWithType.vb: BlobStoragEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule(Of TAuthenticationToken)
  name.vb: BlobStoragEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule`1
    name: BlobStoragEventStoreModule
    nameWithType: BlobStoragEventStoreModule
    fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule`1
    name: BlobStoragEventStoreModule
    nameWithType: BlobStoragEventStoreModule
    fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.BlobStoragEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule`1
  commentId: T:Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule`1
  isExternal: false
  name: TableStoragEventStoreModule<TAuthenticationToken>
  nameWithType: TableStoragEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule<TAuthenticationToken>
  nameWithType.vb: TableStoragEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule(Of TAuthenticationToken)
  name.vb: TableStoragEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule`1
    name: TableStoragEventStoreModule
    nameWithType: TableStoragEventStoreModule
    fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule`1
    name: TableStoragEventStoreModule
    nameWithType: TableStoragEventStoreModule
    fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStoragEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStorageDataStoreModule
  commentId: T:Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStorageDataStoreModule
  isExternal: false
  name: TableStorageDataStoreModule
  nameWithType: TableStorageDataStoreModule
  fullName: Cqrs.Ninject.Azure.BlobStorage.Configuration.TableStorageDataStoreModule
