### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  id: AzureDocumentDbEventStoreModule`1
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration
  children:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.Load
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterAzureHelpers
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterEventStore
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterFactories
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterServices
  langs:
  - csharp
  - vb
  name: AzureDocumentDbEventStoreModule<TAuthenticationToken>
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureDocumentDbEventStoreModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
    startLine: 21
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Events.IEventStore%601\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class AzureDocumentDbEventStoreModule<TAuthenticationToken> : NinjectModule'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureDocumentDbEventStoreModule(Of TAuthenticationToken)

          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule`1
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  name.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken)
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.Load
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.Load
  id: Load
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
    startLine: 28
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.Load*
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).Load()
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).Load()
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterFactories
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterFactories
  id: RegisterFactories
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  langs:
  - csharp
  - vb
  name: RegisterFactories()
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterFactories()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterFactories()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterFactories
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
    startLine: 41
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister the all factories\n"
  example: []
  syntax:
    content: public virtual void RegisterFactories()
    content.vb: Public Overridable Sub RegisterFactories
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterFactories*
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterFactories()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterFactories()
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterServices
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterServices
  id: RegisterServices
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  langs:
  - csharp
  - vb
  name: RegisterServices()
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterServices()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterServices()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterServices
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
    startLine: 54
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister the all services\n"
  example: []
  syntax:
    content: public virtual void RegisterServices()
    content.vb: Public Overridable Sub RegisterServices
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterServices*
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterServices()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterServices()
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterAzureHelpers
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterAzureHelpers
  id: RegisterAzureHelpers
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  langs:
  - csharp
  - vb
  name: RegisterAzureHelpers()
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterAzureHelpers()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterAzureHelpers()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterAzureHelpers
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
    startLine: 61
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister <xref href=\"Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper\" data-throw-if-not-resolved=\"false\"></xref> if it hasn&apos;t already been registered.\n"
  example: []
  syntax:
    content: public virtual void RegisterAzureHelpers()
    content.vb: Public Overridable Sub RegisterAzureHelpers
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterAzureHelpers*
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterAzureHelpers()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterAzureHelpers()
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterEventStore
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterEventStore
  id: RegisterEventStore
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  langs:
  - csharp
  - vb
  name: RegisterEventStore()
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterEventStore()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterEventStore()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterEventStore
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/AzureDocumentDbEventStoreModule.cs
    startLine: 74
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister the <xref href=\"Cqrs.Azure.DocumentDb.Events.IAzureDocumentDbEventStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref> and <xref href=\"Cqrs.Events.IEventStore%601\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: public virtual void RegisterEventStore()
    content.vb: Public Overridable Sub RegisterEventStore
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterEventStore*
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterEventStore()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterEventStore()
references:
- uid: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore`1
  commentId: T:Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore`1
  isExternal: false
  name: AzureDocumentDbEventStore<TAuthenticationToken>
  nameWithType: AzureDocumentDbEventStore<TAuthenticationToken>
  fullName: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore<TAuthenticationToken>
  nameWithType.vb: AzureDocumentDbEventStore(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore(Of TAuthenticationToken)
  name.vb: AzureDocumentDbEventStore(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore`1
    name: AzureDocumentDbEventStore
    nameWithType: AzureDocumentDbEventStore
    fullName: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore`1
    name: AzureDocumentDbEventStore
    nameWithType: AzureDocumentDbEventStore
    fullName: Cqrs.Azure.DocumentDb.Events.AzureDocumentDbEventStore
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Events.IEventStore`1
  commentId: T:Cqrs.Events.IEventStore`1
  isExternal: false
  name: IEventStore<TAuthenticationToken>
  nameWithType: IEventStore<TAuthenticationToken>
  fullName: Cqrs.Events.IEventStore<TAuthenticationToken>
  nameWithType.vb: IEventStore(Of TAuthenticationToken)
  fullName.vb: Cqrs.Events.IEventStore(Of TAuthenticationToken)
  name.vb: IEventStore(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Events.IEventStore`1
    name: IEventStore
    nameWithType: IEventStore
    fullName: Cqrs.Events.IEventStore
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Events.IEventStore`1
    name: IEventStore
    nameWithType: IEventStore
    fullName: Cqrs.Events.IEventStore
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration
  commentId: N:Cqrs.Ninject.Azure.DocumentDb.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.DocumentDb.Configuration
  nameWithType: Cqrs.Ninject.Azure.DocumentDb.Configuration
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.Load*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.Load
  isExternal: false
  name: Load
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.Load
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.Load
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).Load
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).Load
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterFactories*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterFactories
  isExternal: false
  name: RegisterFactories
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterFactories
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterFactories
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterFactories
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterFactories
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterServices*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterServices
  isExternal: false
  name: RegisterServices
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterServices
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterServices
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterServices
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterServices
- uid: Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper
  commentId: T:Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper
  parent: Cqrs.Azure.DocumentDb
  isExternal: false
  name: IAzureDocumentDbHelper
  nameWithType: IAzureDocumentDbHelper
  fullName: Cqrs.Azure.DocumentDb.IAzureDocumentDbHelper
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterAzureHelpers*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterAzureHelpers
  isExternal: false
  name: RegisterAzureHelpers
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterAzureHelpers
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterAzureHelpers
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterAzureHelpers
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterAzureHelpers
- uid: Cqrs.Azure.DocumentDb
  commentId: N:Cqrs.Azure.DocumentDb
  isExternal: false
  name: Cqrs.Azure.DocumentDb
  nameWithType: Cqrs.Azure.DocumentDb
  fullName: Cqrs.Azure.DocumentDb
- uid: Cqrs.Azure.DocumentDb.Events.IAzureDocumentDbEventStoreConnectionStringFactory
  commentId: T:Cqrs.Azure.DocumentDb.Events.IAzureDocumentDbEventStoreConnectionStringFactory
  parent: Cqrs.Azure.DocumentDb.Events
  isExternal: false
  name: IAzureDocumentDbEventStoreConnectionStringFactory
  nameWithType: IAzureDocumentDbEventStoreConnectionStringFactory
  fullName: Cqrs.Azure.DocumentDb.Events.IAzureDocumentDbEventStoreConnectionStringFactory
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterEventStore*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1.RegisterEventStore
  isExternal: false
  name: RegisterEventStore
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterEventStore
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>.RegisterEventStore
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterEventStore
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken).RegisterEventStore
- uid: Cqrs.Azure.DocumentDb.Events
  commentId: N:Cqrs.Azure.DocumentDb.Events
  isExternal: false
  name: Cqrs.Azure.DocumentDb.Events
  nameWithType: Cqrs.Azure.DocumentDb.Events
  fullName: Cqrs.Azure.DocumentDb.Events
