### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration
  commentId: N:Cqrs.Ninject.Azure.DocumentDb.Configuration
  id: Cqrs.Ninject.Azure.DocumentDb.Configuration
  children:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule`1
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Azure.DocumentDb.Configuration
  nameWithType: Cqrs.Ninject.Azure.DocumentDb.Configuration
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
references:
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
  isExternal: false
  name: AzureDocumentDbEventStoreModule<TAuthenticationToken>
  nameWithType: AzureDocumentDbEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule<TAuthenticationToken>
  nameWithType.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  name.vb: AzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
    name: AzureDocumentDbEventStoreModule
    nameWithType: AzureDocumentDbEventStoreModule
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule`1
    name: AzureDocumentDbEventStoreModule
    nameWithType: AzureDocumentDbEventStoreModule
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration
  isExternal: false
  name: AzureDocumentDbModule
  nameWithType: AzureDocumentDbModule
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule`1
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule`1
  isExternal: false
  name: TestAzureDocumentDbEventStoreModule<TAuthenticationToken>
  nameWithType: TestAzureDocumentDbEventStoreModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule<TAuthenticationToken>
  nameWithType.vb: TestAzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  name.vb: TestAzureDocumentDbEventStoreModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule`1
    name: TestAzureDocumentDbEventStoreModule
    nameWithType: TestAzureDocumentDbEventStoreModule
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule`1
    name: TestAzureDocumentDbEventStoreModule
    nameWithType: TestAzureDocumentDbEventStoreModule
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbEventStoreModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  isExternal: false
  name: TestAzureDocumentDbModule
  nameWithType: TestAzureDocumentDbModule
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration
  commentId: N:Cqrs.Ninject.Azure.DocumentDb.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.DocumentDb.Configuration
  nameWithType: Cqrs.Ninject.Azure.DocumentDb.Configuration
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration
