### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.ConfigurationManager
  commentId: N:Cqrs.Azure.ConfigurationManager
  id: Cqrs.Azure.ConfigurationManager
  children:
  - Cqrs.Azure.ConfigurationManager.CloudConfigurationManager
  - Cqrs.Azure.ConfigurationManager.TelemetryCoreHost`1
  langs:
  - csharp
  - vb
  name: Cqrs.Azure.ConfigurationManager
  nameWithType: Cqrs.Azure.ConfigurationManager
  fullName: Cqrs.Azure.ConfigurationManager
  type: Namespace
  assemblies:
  - Cqrs.Azure.ConfigurationManager
references:
- uid: Cqrs.Azure.ConfigurationManager.CloudConfigurationManager
  commentId: T:Cqrs.Azure.ConfigurationManager.CloudConfigurationManager
  isExternal: false
  name: CloudConfigurationManager
  nameWithType: CloudConfigurationManager
  fullName: Cqrs.Azure.ConfigurationManager.CloudConfigurationManager
- uid: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost`1
  commentId: T:Cqrs.Azure.ConfigurationManager.TelemetryCoreHost`1
  isExternal: false
  name: TelemetryCoreHost<TAuthenticationToken>
  nameWithType: TelemetryCoreHost<TAuthenticationToken>
  fullName: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost<TAuthenticationToken>
  nameWithType.vb: TelemetryCoreHost(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost(Of TAuthenticationToken)
  name.vb: TelemetryCoreHost(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost`1
    name: TelemetryCoreHost
    nameWithType: TelemetryCoreHost
    fullName: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost`1
    name: TelemetryCoreHost
    nameWithType: TelemetryCoreHost
    fullName: Cqrs.Azure.ConfigurationManager.TelemetryCoreHost
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
