### YamlMime:ManagedReference
items:
- uid: Cqrs.WebApi.Configuration
  commentId: N:Cqrs.WebApi.Configuration
  id: Cqrs.WebApi.Configuration
  children:
  - Cqrs.WebApi.Configuration.WebApiConfig
  langs:
  - csharp
  - vb
  name: Cqrs.WebApi.Configuration
  nameWithType: Cqrs.WebApi.Configuration
  fullName: Cqrs.WebApi.Configuration
  type: Namespace
  assemblies:
  - Cqrs.WebApi
references:
- uid: Cqrs.WebApi.Configuration.WebApiConfig
  commentId: T:Cqrs.WebApi.Configuration.WebApiConfig
  isExternal: false
  name: WebApiConfig
  nameWithType: WebApiConfig
  fullName: Cqrs.WebApi.Configuration.WebApiConfig
