### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.InProcess.EventBus.Configuration
  commentId: N:Cqrs.Ninject.InProcess.EventBus.Configuration
  id: Cqrs.Ninject.InProcess.EventBus.Configuration
  children:
  - Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.InProcess.EventBus.Configuration
  nameWithType: Cqrs.Ninject.InProcess.EventBus.Configuration
  fullName: Cqrs.Ninject.InProcess.EventBus.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.InProcess.EventBus
references:
- uid: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule`1
  commentId: T:Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule`1
  isExternal: false
  name: InProcessEventBusModule<TAuthenticationToken>
  nameWithType: InProcessEventBusModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule<TAuthenticationToken>
  nameWithType.vb: InProcessEventBusModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule(Of TAuthenticationToken)
  name.vb: InProcessEventBusModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule`1
    name: InProcessEventBusModule
    nameWithType: InProcessEventBusModule
    fullName: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule`1
    name: InProcessEventBusModule
    nameWithType: InProcessEventBusModule
    fullName: Cqrs.Ninject.InProcess.EventBus.Configuration.InProcessEventBusModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
