### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.InProcess.CommandBus.Configuration
  commentId: N:Cqrs.Ninject.InProcess.CommandBus.Configuration
  id: Cqrs.Ninject.InProcess.CommandBus.Configuration
  children:
  - Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.InProcess.CommandBus.Configuration
  nameWithType: Cqrs.Ninject.InProcess.CommandBus.Configuration
  fullName: Cqrs.Ninject.InProcess.CommandBus.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.InProcess.CommandBus
references:
- uid: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule`1
  commentId: T:Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule`1
  isExternal: false
  name: InProcessCommandBusModule<TAuthenticationToken>
  nameWithType: InProcessCommandBusModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule<TAuthenticationToken>
  nameWithType.vb: InProcessCommandBusModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule(Of TAuthenticationToken)
  name.vb: InProcessCommandBusModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule`1
    name: InProcessCommandBusModule
    nameWithType: InProcessCommandBusModule
    fullName: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule`1
    name: InProcessCommandBusModule
    nameWithType: InProcessCommandBusModule
    fullName: Cqrs.Ninject.InProcess.CommandBus.Configuration.InProcessCommandBusModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
