### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  commentId: T:Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  id: TestMongoModule
  parent: Cqrs.Ninject.Mongo.Configuration
  children:
  - Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories
  langs:
  - csharp
  - vb
  name: TestMongoModule
  nameWithType: TestMongoModule
  fullName: Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  type: Class
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/TestMongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: TestMongoModule
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/TestMongoModule.cs
    startLine: 17
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Ninject.Mongo.TestMongoDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref> as the\n<xref href=\"Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class TestMongoModule : MongoModule'
    content.vb: >-
      Public Class TestMongoModule

          Inherits MongoModule
  inheritance:
  - System.Object
  - Cqrs.Ninject.Mongo.Configuration.MongoModule
  inheritedMembers:
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  - Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories
  commentId: M:Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories
  id: RegisterFactories
  parent: Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  langs:
  - csharp
  - vb
  name: RegisterFactories()
  nameWithType: TestMongoModule.RegisterFactories()
  fullName: Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/TestMongoModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterFactories
    path: Framework/Ninject/Cqrs.Ninject.Mongo/Configuration/TestMongoModule.cs
    startLine: 22
  assemblies:
  - Cqrs.Ninject.Mongo
  namespace: Cqrs.Ninject.Mongo.Configuration
  summary: "\nRegister the all factories\n"
  example: []
  syntax:
    content: public override void RegisterFactories()
    content.vb: Public Overrides Sub RegisterFactories
  overridden: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  overload: Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Cqrs.Ninject.Mongo.TestMongoDataStoreConnectionStringFactory
  commentId: T:Cqrs.Ninject.Mongo.TestMongoDataStoreConnectionStringFactory
  isExternal: false
  name: TestMongoDataStoreConnectionStringFactory
  nameWithType: TestMongoDataStoreConnectionStringFactory
  fullName: Cqrs.Ninject.Mongo.TestMongoDataStoreConnectionStringFactory
- uid: Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory
  commentId: T:Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory
  parent: Cqrs.Mongo.Factories
  isExternal: false
  name: IMongoDataStoreConnectionStringFactory
  nameWithType: IMongoDataStoreConnectionStringFactory
  fullName: Cqrs.Mongo.Factories.IMongoDataStoreConnectionStringFactory
- uid: Cqrs.Ninject.Mongo.Configuration
  commentId: N:Cqrs.Ninject.Mongo.Configuration
  isExternal: false
  name: Cqrs.Ninject.Mongo.Configuration
  nameWithType: Cqrs.Ninject.Mongo.Configuration
  fullName: Cqrs.Ninject.Mongo.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule
  commentId: T:Cqrs.Ninject.Mongo.Configuration.MongoModule
  parent: Cqrs.Ninject.Mongo.Configuration
  isExternal: false
  name: MongoModule
  nameWithType: MongoModule
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  isExternal: false
  name: Load()
  nameWithType: MongoModule.Load()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load()
  spec.csharp:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
    name: Load
    nameWithType: MongoModule.Load
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
    name: Load
    nameWithType: MongoModule.Load
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  isExternal: false
  name: RegisterServices()
  nameWithType: MongoModule.RegisterServices()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices()
  spec.csharp:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
    name: RegisterServices
    nameWithType: MongoModule.RegisterServices
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
    name: RegisterServices
    nameWithType: MongoModule.RegisterServices
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterServices
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  isExternal: false
  name: RegisterCqrsRequirements()
  nameWithType: MongoModule.RegisterCqrsRequirements()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements()
  spec.csharp:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
    name: RegisterCqrsRequirements
    nameWithType: MongoModule.RegisterCqrsRequirements
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
    name: RegisterCqrsRequirements
    nameWithType: MongoModule.RegisterCqrsRequirements
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterCqrsRequirements
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Mongo.Factories
  commentId: N:Cqrs.Mongo.Factories
  isExternal: false
  name: Cqrs.Mongo.Factories
  nameWithType: Cqrs.Mongo.Factories
  fullName: Cqrs.Mongo.Factories
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  commentId: M:Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  parent: Cqrs.Ninject.Mongo.Configuration.MongoModule
  isExternal: false
  name: RegisterFactories()
  nameWithType: MongoModule.RegisterFactories()
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories()
  spec.csharp:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
    name: RegisterFactories
    nameWithType: MongoModule.RegisterFactories
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
    name: RegisterFactories
    nameWithType: MongoModule.RegisterFactories
    fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule.RegisterFactories
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories*
  commentId: Overload:Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories
  isExternal: false
  name: RegisterFactories
  nameWithType: TestMongoModule.RegisterFactories
  fullName: Cqrs.Ninject.Mongo.Configuration.TestMongoModule.RegisterFactories
