### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  id: AzureCommandHubReceiverModule`1
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration
  children:
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  langs:
  - csharp
  - vb
  name: AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureCommandHubReceiverModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
    startLine: 21
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureCommandBusReceiver%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Commands.ICommandReceiver\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureCommandHubReceiverModule<TAuthenticationToken> : NinjectModule'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureCommandHubReceiverModule(Of TAuthenticationToken)
          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureQueuedCommandHubReceiverModule`1
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  id: Load
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
    startLine: 28
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load*
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).Load()
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).Load()
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  id: RegisterCommandHandlerRegistrar
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: RegisterCommandHandlerRegistrar()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterCommandHandlerRegistrar
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
    startLine: 47
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nRegister the CQRS command handler registrar\n"
  example: []
  syntax:
    content: public virtual void RegisterCommandHandlerRegistrar()
    content.vb: Public Overridable Sub RegisterCommandHandlerRegistrar
  overload: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar*
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar()
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  id: RegisterCommandMessageSerialiser
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: RegisterCommandMessageSerialiser()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterCommandMessageSerialiser
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubReceiverModule.cs
    startLine: 57
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nRegister the CQRS command handler message serialiser\n"
  example: []
  syntax:
    content: public virtual void RegisterCommandMessageSerialiser()
    content.vb: Public Overridable Sub RegisterCommandMessageSerialiser
  overload: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser*
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
references:
- uid: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
  isExternal: false
  name: AzureCommandBusReceiver<TAuthenticationToken>
  nameWithType: AzureCommandBusReceiver<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusReceiver(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver(Of TAuthenticationToken)
  name.vb: AzureCommandBusReceiver(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
    name: AzureCommandBusReceiver
    nameWithType: AzureCommandBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
    name: AzureCommandBusReceiver
    nameWithType: AzureCommandBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Commands.ICommandReceiver
  commentId: T:Cqrs.Commands.ICommandReceiver
  parent: Cqrs.Commands
  isExternal: false
  name: ICommandReceiver
  nameWithType: ICommandReceiver
  fullName: Cqrs.Commands.ICommandReceiver
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.CommandBus.Configuration
  isExternal: false
  name: Cqrs.Azure.EventHub.CommandBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.CommandBus.Configuration
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Commands
  commentId: N:Cqrs.Commands
  isExternal: false
  name: Cqrs.Commands
  nameWithType: Cqrs.Commands
  fullName: Cqrs.Commands
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load*
  commentId: Overload:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  isExternal: false
  name: Load
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.Load
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.Load
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).Load
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).Load
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar*
  commentId: Overload:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  isExternal: false
  name: RegisterCommandHandlerRegistrar
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser*
  commentId: Overload:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  isExternal: false
  name: RegisterCommandMessageSerialiser
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
