### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration
  commentId: N:Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration
  id: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration
  children:
  - Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  - Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  - Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule`1
  - Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration
  nameWithType: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration
  fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Azure.ServiceBus.CommandBus
references:
- uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule`1
  isExternal: false
  name: AzureCommandBusSenderModule<TAuthenticationToken>
  nameWithType: AzureCommandBusSenderModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusSenderModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusSenderModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule`1
    name: AzureCommandBusSenderModule
    nameWithType: AzureCommandBusSenderModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule`1
    name: AzureCommandBusSenderModule
    nameWithType: AzureCommandBusSenderModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusSenderModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  isExternal: false
  name: AzureCommandBusPublisherModule<TAuthenticationToken>
  nameWithType: AzureCommandBusPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule`1
    name: AzureCommandBusPublisherModule
    nameWithType: AzureCommandBusPublisherModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule`1
    name: AzureCommandBusPublisherModule
    nameWithType: AzureCommandBusPublisherModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  isExternal: false
  name: AzureCommandBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule`1
    name: AzureCommandBusReceiverModule
    nameWithType: AzureCommandBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule`1
    name: AzureCommandBusReceiverModule
    nameWithType: AzureCommandBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureCommandBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
  isExternal: false
  name: AzureQueuedCommandBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureQueuedCommandBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureQueuedCommandBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureQueuedCommandBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
    name: AzureQueuedCommandBusReceiverModule
    nameWithType: AzureQueuedCommandBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule`1
    name: AzureQueuedCommandBusReceiverModule
    nameWithType: AzureQueuedCommandBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.CommandBus.Configuration.AzureQueuedCommandBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
