### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule`1
  id: AzureCommandBusReceiverModule`1
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: AzureCommandBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandBusReceiverModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureCommandBusReceiverModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandBusReceiverModule.cs
    startLine: 19
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureCommandBusReceiver%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Commands.ICommandReceiver\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureCommandBusReceiverModule<TAuthenticationToken> : AzureCommandHubReceiverModule<TAuthenticationToken>'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureCommandBusReceiverModule(Of TAuthenticationToken)

          Inherits AzureCommandHubReceiverModule(Of TAuthenticationToken)
  inheritance:
  - System.Object
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}
  inheritedMembers:
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}.Load
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}.RegisterCommandHandlerRegistrar
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}.RegisterCommandMessageSerialiser
  nameWithType.vb: AzureCommandBusReceiverModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandBusReceiverModule(Of TAuthenticationToken)
references:
- uid: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
  isExternal: false
  name: AzureCommandBusReceiver<TAuthenticationToken>
  nameWithType: AzureCommandBusReceiver<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusReceiver(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver(Of TAuthenticationToken)
  name.vb: AzureCommandBusReceiver(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
    name: AzureCommandBusReceiver
    nameWithType: AzureCommandBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver`1
    name: AzureCommandBusReceiver
    nameWithType: AzureCommandBusReceiver
    fullName: Cqrs.Azure.ServiceBus.AzureCommandBusReceiver
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Commands.ICommandReceiver
  commentId: T:Cqrs.Commands.ICommandReceiver
  parent: Cqrs.Commands
  isExternal: false
  name: ICommandReceiver
  nameWithType: ICommandReceiver
  fullName: Cqrs.Commands.ICommandReceiver
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.CommandBus.Configuration
  isExternal: false
  name: Cqrs.Azure.EventHub.CommandBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.CommandBus.Configuration
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{`0}
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration
  definition: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  name: AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
    name: AzureCommandHubReceiverModule
    nameWithType: AzureCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
    name: AzureCommandHubReceiverModule
    nameWithType: AzureCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}.Load
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{`0}.Load
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  name: Load()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.Load()
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).Load()
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).Load()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.Load
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureCommandHubReceiverModule(Of TAuthenticationToken).Load
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}.RegisterCommandHandlerRegistrar
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{`0}.RegisterCommandHandlerRegistrar
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  name: RegisterCommandHandlerRegistrar()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar()
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar()
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
    name: RegisterCommandHandlerRegistrar
    nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
    name: RegisterCommandHandlerRegistrar
    nameWithType: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}.RegisterCommandMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{`0}.RegisterCommandMessageSerialiser
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  name: RegisterCommandMessageSerialiser()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
    name: RegisterCommandMessageSerialiser
    nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
    name: RegisterCommandMessageSerialiser
    nameWithType: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Commands
  commentId: N:Cqrs.Commands
  isExternal: false
  name: Cqrs.Commands
  nameWithType: Cqrs.Commands
  fullName: Cqrs.Commands
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
  isExternal: false
  name: AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
    name: AzureCommandHubReceiverModule
    nameWithType: AzureCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1
    name: AzureCommandHubReceiverModule
    nameWithType: AzureCommandHubReceiverModule
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
  isExternal: false
  name: Load()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.Load()
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).Load()
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).Load()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.Load
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.Load
    name: Load
    nameWithType: AzureCommandHubReceiverModule(Of TAuthenticationToken).Load
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
  isExternal: false
  name: RegisterCommandHandlerRegistrar()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar()
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar()
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
    name: RegisterCommandHandlerRegistrar
    nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandHandlerRegistrar
    name: RegisterCommandHandlerRegistrar
    nameWithType: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandHandlerRegistrar
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
  isExternal: false
  name: RegisterCommandMessageSerialiser()
  nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  nameWithType.vb: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
    name: RegisterCommandMessageSerialiser
    nameWithType: AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule`1.RegisterCommandMessageSerialiser
    name: RegisterCommandMessageSerialiser
    nameWithType: AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
    fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubReceiverModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
