### YamlMime:ManagedReference
items:
- uid: Cqrs.Akka.Configuration
  commentId: N:Cqrs.Akka.Configuration
  id: Cqrs.Akka.Configuration
  children:
  - Cqrs.Akka.Configuration.AkkaBusRegistrar`1
  - Cqrs.Akka.Configuration.IHandlerResolver
  langs:
  - csharp
  - vb
  name: Cqrs.Akka.Configuration
  nameWithType: Cqrs.Akka.Configuration
  fullName: Cqrs.Akka.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Akka
references:
- uid: Cqrs.Akka.Configuration.AkkaBusRegistrar`1
  commentId: T:Cqrs.Akka.Configuration.AkkaBusRegistrar`1
  isExternal: false
  name: AkkaBusRegistrar<TAuthenticationToken>
  nameWithType: AkkaBusRegistrar<TAuthenticationToken>
  fullName: Cqrs.Akka.Configuration.AkkaBusRegistrar<TAuthenticationToken>
  nameWithType.vb: AkkaBusRegistrar(Of TAuthenticationToken)
  fullName.vb: Cqrs.Akka.Configuration.AkkaBusRegistrar(Of TAuthenticationToken)
  name.vb: AkkaBusRegistrar(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Akka.Configuration.AkkaBusRegistrar`1
    name: AkkaBusRegistrar
    nameWithType: AkkaBusRegistrar
    fullName: Cqrs.Akka.Configuration.AkkaBusRegistrar
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Akka.Configuration.AkkaBusRegistrar`1
    name: AkkaBusRegistrar
    nameWithType: AkkaBusRegistrar
    fullName: Cqrs.Akka.Configuration.AkkaBusRegistrar
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Akka.Configuration.IHandlerResolver
  commentId: T:Cqrs.Akka.Configuration.IHandlerResolver
  parent: Cqrs.Akka.Configuration
  isExternal: false
  name: IHandlerResolver
  nameWithType: IHandlerResolver
  fullName: Cqrs.Akka.Configuration.IHandlerResolver
- uid: Cqrs.Akka.Configuration
  commentId: N:Cqrs.Akka.Configuration
  isExternal: false
  name: Cqrs.Akka.Configuration
  nameWithType: Cqrs.Akka.Configuration
  fullName: Cqrs.Akka.Configuration
