### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  id: AzureCommandHubPublisherModule`1
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration
  children:
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.Load
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandMessageSerialiser
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandSender
  langs:
  - csharp
  - vb
  name: AzureCommandHubPublisherModule<TAuthenticationToken>
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureCommandHubPublisherModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
    startLine: 20
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureCommandBusPublisher%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Commands.ICommandPublisher%601\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureCommandHubPublisherModule<TAuthenticationToken> : NinjectModule'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureCommandHubPublisherModule(Of TAuthenticationToken)

          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusPublisherModule`1
  - Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandBusSenderModule`1
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken)
  name.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken)
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.Load
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.Load
  id: Load
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
    startLine: 27
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.Load*
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken).Load()
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken).Load()
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandSender
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandSender
  id: RegisterCommandSender
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  langs:
  - csharp
  - vb
  name: RegisterCommandSender()
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandSender()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandSender()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterCommandSender
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
    startLine: 46
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nRegister the CQRS command publisher\n"
  example: []
  syntax:
    content: public virtual void RegisterCommandSender()
    content.vb: Public Overridable Sub RegisterCommandSender
  overload: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandSender*
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandSender()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandSender()
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandMessageSerialiser
  id: RegisterCommandMessageSerialiser
  parent: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1
  langs:
  - csharp
  - vb
  name: RegisterCommandMessageSerialiser()
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandMessageSerialiser()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterCommandMessageSerialiser
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.CommandBus/Configuration/AzureCommandHubPublisherModule.cs
    startLine: 64
  assemblies:
  - Cqrs.Azure.EventHub.CommandBus
  namespace: Cqrs.Azure.EventHub.CommandBus.Configuration
  summary: "\nRegister the CQRS command handler message serialiser\n"
  example: []
  syntax:
    content: public virtual void RegisterCommandMessageSerialiser()
    content.vb: Public Overridable Sub RegisterCommandMessageSerialiser
  overload: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandMessageSerialiser*
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser()
references:
- uid: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureCommandBusPublisher`1
  isExternal: false
  name: AzureCommandBusPublisher<TAuthenticationToken>
  nameWithType: AzureCommandBusPublisher<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher<TAuthenticationToken>
  nameWithType.vb: AzureCommandBusPublisher(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher(Of TAuthenticationToken)
  name.vb: AzureCommandBusPublisher(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher`1
    name: AzureCommandBusPublisher
    nameWithType: AzureCommandBusPublisher
    fullName: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher`1
    name: AzureCommandBusPublisher
    nameWithType: AzureCommandBusPublisher
    fullName: Cqrs.Azure.ServiceBus.AzureCommandBusPublisher
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Commands.ICommandPublisher`1
  commentId: T:Cqrs.Commands.ICommandPublisher`1
  isExternal: false
  name: ICommandPublisher<TAuthenticationToken>
  nameWithType: ICommandPublisher<TAuthenticationToken>
  fullName: Cqrs.Commands.ICommandPublisher<TAuthenticationToken>
  nameWithType.vb: ICommandPublisher(Of TAuthenticationToken)
  fullName.vb: Cqrs.Commands.ICommandPublisher(Of TAuthenticationToken)
  name.vb: ICommandPublisher(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Commands.ICommandPublisher`1
    name: ICommandPublisher
    nameWithType: ICommandPublisher
    fullName: Cqrs.Commands.ICommandPublisher
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Commands.ICommandPublisher`1
    name: ICommandPublisher
    nameWithType: ICommandPublisher
    fullName: Cqrs.Commands.ICommandPublisher
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.CommandBus.Configuration
  isExternal: false
  name: Cqrs.Azure.EventHub.CommandBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.CommandBus.Configuration
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.Load*
  commentId: Overload:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.Load
  isExternal: false
  name: Load
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>.Load
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>.Load
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken).Load
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken).Load
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandSender*
  commentId: Overload:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandSender
  isExternal: false
  name: RegisterCommandSender
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandSender
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandSender
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandSender
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandSender
- uid: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandMessageSerialiser*
  commentId: Overload:Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule`1.RegisterCommandMessageSerialiser
  isExternal: false
  name: RegisterCommandMessageSerialiser
  nameWithType: AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
  fullName: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule<TAuthenticationToken>.RegisterCommandMessageSerialiser
  nameWithType.vb: AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
  fullName.vb: Cqrs.Azure.EventHub.CommandBus.Configuration.AzureCommandHubPublisherModule(Of TAuthenticationToken).RegisterCommandMessageSerialiser
