### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Akka.Configuration
  commentId: N:Cqrs.Ninject.Akka.Configuration
  id: Cqrs.Ninject.Akka.Configuration
  children:
  - Cqrs.Ninject.Akka.Configuration.AkkaModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Akka.Configuration
  nameWithType: Cqrs.Ninject.Akka.Configuration
  fullName: Cqrs.Ninject.Akka.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Akka
references:
- uid: Cqrs.Ninject.Akka.Configuration.AkkaModule`1
  commentId: T:Cqrs.Ninject.Akka.Configuration.AkkaModule`1
  isExternal: false
  name: AkkaModule<TAuthenticationToken>
  nameWithType: AkkaModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Akka.Configuration.AkkaModule<TAuthenticationToken>
  nameWithType.vb: AkkaModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Akka.Configuration.AkkaModule(Of TAuthenticationToken)
  name.vb: AkkaModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Akka.Configuration.AkkaModule`1
    name: AkkaModule
    nameWithType: AkkaModule
    fullName: Cqrs.Ninject.Akka.Configuration.AkkaModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Akka.Configuration.AkkaModule`1
    name: AkkaModule
    nameWithType: AkkaModule
    fullName: Cqrs.Ninject.Akka.Configuration.AkkaModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
