### YamlMime:ManagedReference
items:
- uid: Cqrs.Configuration
  commentId: N:Cqrs.Configuration
  id: Cqrs.Configuration
  children:
  - Cqrs.Configuration.BusRegistrar
  - Cqrs.Configuration.ConfigurationExtensions
  - Cqrs.Configuration.ConfigurationManager
  - Cqrs.Configuration.DependencyResolver
  - Cqrs.Configuration.HandlerDelegate
  - Cqrs.Configuration.HandlerDelegate`1
  - Cqrs.Configuration.IConfigurationManager
  - Cqrs.Configuration.IDependencyResolver
  - Cqrs.Configuration.ITelemetryHelperExtensions
  langs:
  - csharp
  - vb
  name: Cqrs.Configuration
  nameWithType: Cqrs.Configuration
  fullName: Cqrs.Configuration
  type: Namespace
  assemblies:
  - Cqrs
references:
- uid: Cqrs.Configuration.ConfigurationExtensions
  commentId: T:Cqrs.Configuration.ConfigurationExtensions
  parent: Cqrs.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Cqrs.Configuration.ConfigurationExtensions
- uid: Cqrs.Configuration.ConfigurationManager
  commentId: T:Cqrs.Configuration.ConfigurationManager
  parent: Cqrs.Configuration
  isExternal: false
  name: ConfigurationManager
  nameWithType: ConfigurationManager
  fullName: Cqrs.Configuration.ConfigurationManager
- uid: Cqrs.Configuration.DependencyResolver
  commentId: T:Cqrs.Configuration.DependencyResolver
  parent: Cqrs.Configuration
  isExternal: false
  name: DependencyResolver
  nameWithType: DependencyResolver
  fullName: Cqrs.Configuration.DependencyResolver
- uid: Cqrs.Configuration.HandlerDelegate
  commentId: T:Cqrs.Configuration.HandlerDelegate
  parent: Cqrs.Configuration
  isExternal: false
  name: HandlerDelegate
  nameWithType: HandlerDelegate
  fullName: Cqrs.Configuration.HandlerDelegate
- uid: Cqrs.Configuration.HandlerDelegate`1
  commentId: T:Cqrs.Configuration.HandlerDelegate`1
  isExternal: false
  name: HandlerDelegate<T>
  nameWithType: HandlerDelegate<T>
  fullName: Cqrs.Configuration.HandlerDelegate<T>
  nameWithType.vb: HandlerDelegate(Of T)
  fullName.vb: Cqrs.Configuration.HandlerDelegate(Of T)
  name.vb: HandlerDelegate(Of T)
  spec.csharp:
  - uid: Cqrs.Configuration.HandlerDelegate`1
    name: HandlerDelegate
    nameWithType: HandlerDelegate
    fullName: Cqrs.Configuration.HandlerDelegate
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Configuration.HandlerDelegate`1
    name: HandlerDelegate
    nameWithType: HandlerDelegate
    fullName: Cqrs.Configuration.HandlerDelegate
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Configuration.IConfigurationManager
  commentId: T:Cqrs.Configuration.IConfigurationManager
  parent: Cqrs.Configuration
  isExternal: false
  name: IConfigurationManager
  nameWithType: IConfigurationManager
  fullName: Cqrs.Configuration.IConfigurationManager
- uid: Cqrs.Configuration.IDependencyResolver
  commentId: T:Cqrs.Configuration.IDependencyResolver
  parent: Cqrs.Configuration
  isExternal: false
  name: IDependencyResolver
  nameWithType: IDependencyResolver
  fullName: Cqrs.Configuration.IDependencyResolver
- uid: Cqrs.Configuration.ITelemetryHelperExtensions
  commentId: T:Cqrs.Configuration.ITelemetryHelperExtensions
  isExternal: false
  name: ITelemetryHelperExtensions
  nameWithType: ITelemetryHelperExtensions
  fullName: Cqrs.Configuration.ITelemetryHelperExtensions
- uid: Cqrs.Configuration.BusRegistrar
  commentId: T:Cqrs.Configuration.BusRegistrar
  parent: Cqrs.Configuration
  isExternal: false
  name: BusRegistrar
  nameWithType: BusRegistrar
  fullName: Cqrs.Configuration.BusRegistrar
- uid: Cqrs.Configuration
  commentId: N:Cqrs.Configuration
  isExternal: false
  name: Cqrs.Configuration
  nameWithType: Cqrs.Configuration
  fullName: Cqrs.Configuration
