### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Mongo.Configuration
  commentId: N:Cqrs.Ninject.Mongo.Configuration
  id: Cqrs.Ninject.Mongo.Configuration
  children:
  - Cqrs.Ninject.Mongo.Configuration.MongoModule
  - Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Mongo.Configuration
  nameWithType: Cqrs.Ninject.Mongo.Configuration
  fullName: Cqrs.Ninject.Mongo.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Mongo
references:
- uid: Cqrs.Ninject.Mongo.Configuration.MongoModule
  commentId: T:Cqrs.Ninject.Mongo.Configuration.MongoModule
  parent: Cqrs.Ninject.Mongo.Configuration
  isExternal: false
  name: MongoModule
  nameWithType: MongoModule
  fullName: Cqrs.Ninject.Mongo.Configuration.MongoModule
- uid: Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  commentId: T:Cqrs.Ninject.Mongo.Configuration.TestMongoModule
  isExternal: false
  name: TestMongoModule
  nameWithType: TestMongoModule
  fullName: Cqrs.Ninject.Mongo.Configuration.TestMongoModule
- uid: Cqrs.Ninject.Mongo.Configuration
  commentId: N:Cqrs.Ninject.Mongo.Configuration
  isExternal: false
  name: Cqrs.Ninject.Mongo.Configuration
  nameWithType: Cqrs.Ninject.Mongo.Configuration
  fullName: Cqrs.Ninject.Mongo.Configuration
