### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  id: AzureEventBusPublisherModule`1
  parent: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  children:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.Load
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventMessageSerialiser
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventPublisher
  langs:
  - csharp
  - vb
  name: AzureEventBusPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureEventBusPublisherModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
    startLine: 20
  assemblies:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus
  namespace: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureEventBusPublisher%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Events.IEventPublisher%601\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureEventBusPublisherModule<TAuthenticationToken> : NinjectModule'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureEventBusPublisherModule(Of TAuthenticationToken)
          Inherits NinjectModule
  inheritance:
  - System.Object
  derivedClasses:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule`1
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventBusPublisherModule(Of TAuthenticationToken)
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.Load
  commentId: M:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.Load
  id: Load
  parent: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>.Load()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: Load
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
    startLine: 27
  assemblies:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus
  namespace: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  summary: "\nLoads the module into the kernel.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.Load*
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken).Load()
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken).Load()
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventPublisher
  commentId: M:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventPublisher
  id: RegisterEventPublisher
  parent: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  langs:
  - csharp
  - vb
  name: RegisterEventPublisher()
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventPublisher()
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventPublisher()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterEventPublisher
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
    startLine: 46
  assemblies:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus
  namespace: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  summary: "\nRegister the CQRS event publisher\n"
  example: []
  syntax:
    content: public virtual void RegisterEventPublisher()
    content.vb: Public Overridable Sub RegisterEventPublisher
  overload: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventPublisher*
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventPublisher()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventPublisher()
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventMessageSerialiser
  commentId: M:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventMessageSerialiser
  id: RegisterEventMessageSerialiser
  parent: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  langs:
  - csharp
  - vb
  name: RegisterEventMessageSerialiser()
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterEventMessageSerialiser
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.ServiceBus.EventBus/Configuration/AzureEventBusPublisherModule.cs
    startLine: 56
  assemblies:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus
  namespace: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  summary: "\nRegister the CQRS event handler message serialiser\n"
  example: []
  syntax:
    content: public virtual void RegisterEventMessageSerialiser()
    content.vb: Public Overridable Sub RegisterEventMessageSerialiser
  overload: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventMessageSerialiser*
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
references:
- uid: Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
  isExternal: false
  name: AzureEventBusPublisher<TAuthenticationToken>
  nameWithType: AzureEventBusPublisher<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureEventBusPublisher<TAuthenticationToken>
  nameWithType.vb: AzureEventBusPublisher(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureEventBusPublisher(Of TAuthenticationToken)
  name.vb: AzureEventBusPublisher(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
    name: AzureEventBusPublisher
    nameWithType: AzureEventBusPublisher
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusPublisher
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
    name: AzureEventBusPublisher
    nameWithType: AzureEventBusPublisher
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusPublisher
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Events.IEventPublisher`1
  commentId: T:Cqrs.Events.IEventPublisher`1
  isExternal: false
  name: IEventPublisher<TAuthenticationToken>
  nameWithType: IEventPublisher<TAuthenticationToken>
  fullName: Cqrs.Events.IEventPublisher<TAuthenticationToken>
  nameWithType.vb: IEventPublisher(Of TAuthenticationToken)
  fullName.vb: Cqrs.Events.IEventPublisher(Of TAuthenticationToken)
  name.vb: IEventPublisher(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Events.IEventPublisher`1
    name: IEventPublisher
    nameWithType: IEventPublisher
    fullName: Cqrs.Events.IEventPublisher
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Events.IEventPublisher`1
    name: IEventPublisher
    nameWithType: IEventPublisher
    fullName: Cqrs.Events.IEventPublisher
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  commentId: N:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  nameWithType: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.Load*
  commentId: Overload:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.Load
  isExternal: false
  name: Load
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>.Load
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>.Load
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken).Load
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken).Load
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventPublisher*
  commentId: Overload:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventPublisher
  isExternal: false
  name: RegisterEventPublisher
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventPublisher
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventPublisher
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventPublisher
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventPublisher
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventMessageSerialiser*
  commentId: Overload:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1.RegisterEventMessageSerialiser
  isExternal: false
  name: RegisterEventMessageSerialiser
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
