### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  commentId: N:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  id: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  children:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule`1
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule`1
  - Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  nameWithType: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Ninject.Azure.ServiceBus.EventBus
references:
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule`1
  isExternal: false
  name: AzureEventBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureEventBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule`1
    name: AzureEventBusReceiverModule
    nameWithType: AzureEventBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule`1
    name: AzureEventBusReceiverModule
    nameWithType: AzureEventBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
  isExternal: false
  name: AzureEventBusPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventBusPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
    name: AzureEventBusPublisherModule
    nameWithType: AzureEventBusPublisherModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule`1
    name: AzureEventBusPublisherModule
    nameWithType: AzureEventBusPublisherModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventBusPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule`1
  isExternal: false
  name: AzureEventPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule`1
    name: AzureEventPublisherModule
    nameWithType: AzureEventPublisherModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule`1
    name: AzureEventPublisherModule
    nameWithType: AzureEventPublisherModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureEventPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
  commentId: T:Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
  isExternal: false
  name: AzureQueuedEventBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureQueuedEventBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureQueuedEventBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureQueuedEventBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
    name: AzureQueuedEventBusReceiverModule
    nameWithType: AzureQueuedEventBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
    name: AzureQueuedEventBusReceiverModule
    nameWithType: AzureQueuedEventBusReceiverModule
    fullName: Cqrs.Ninject.Azure.ServiceBus.EventBus.Configuration.AzureQueuedEventBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
