### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
  id: AzureEventPublisherModule`1
  parent: Cqrs.Azure.EventHub.EventBus.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: AzureEventPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule<TAuthenticationToken>
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventPublisherModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: AzureEventPublisherModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.EventHub.EventBus/Configuration/AzureEventPublisherModule.cs
    startLine: 19
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
  namespace: Cqrs.Azure.EventHub.EventBus.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Azure.ServiceBus.AzureEventBusPublisher%601\" data-throw-if-not-resolved=\"false\"></xref> as the <xref href=\"Cqrs.Events.IEventPublisher%601\" data-throw-if-not-resolved=\"false\"></xref> and other require components.\n"
  example: []
  syntax:
    content: 'public class AzureEventPublisherModule<TAuthenticationToken> : AzureEventHubPublisherModule<TAuthenticationToken>'
    typeParameters:
    - id: TAuthenticationToken
      description: The <see cref="!:Type"></see> of the authentication token.
    content.vb: >-
      Public Class AzureEventPublisherModule(Of TAuthenticationToken)

          Inherits AzureEventHubPublisherModule(Of TAuthenticationToken)
  inheritance:
  - System.Object
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}
  inheritedMembers:
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}.Load
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}.RegisterEventPublisher
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}.RegisterEventMessageSerialiser
  nameWithType.vb: AzureEventPublisherModule(Of TAuthenticationToken)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventPublisherModule(Of TAuthenticationToken)
references:
- uid: Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
  commentId: T:Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
  isExternal: false
  name: AzureEventBusPublisher<TAuthenticationToken>
  nameWithType: AzureEventBusPublisher<TAuthenticationToken>
  fullName: Cqrs.Azure.ServiceBus.AzureEventBusPublisher<TAuthenticationToken>
  nameWithType.vb: AzureEventBusPublisher(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.ServiceBus.AzureEventBusPublisher(Of TAuthenticationToken)
  name.vb: AzureEventBusPublisher(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
    name: AzureEventBusPublisher
    nameWithType: AzureEventBusPublisher
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusPublisher
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.ServiceBus.AzureEventBusPublisher`1
    name: AzureEventBusPublisher
    nameWithType: AzureEventBusPublisher
    fullName: Cqrs.Azure.ServiceBus.AzureEventBusPublisher
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Events.IEventPublisher`1
  commentId: T:Cqrs.Events.IEventPublisher`1
  isExternal: false
  name: IEventPublisher<TAuthenticationToken>
  nameWithType: IEventPublisher<TAuthenticationToken>
  fullName: Cqrs.Events.IEventPublisher<TAuthenticationToken>
  nameWithType.vb: IEventPublisher(Of TAuthenticationToken)
  fullName.vb: Cqrs.Events.IEventPublisher(Of TAuthenticationToken)
  name.vb: IEventPublisher(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Events.IEventPublisher`1
    name: IEventPublisher
    nameWithType: IEventPublisher
    fullName: Cqrs.Events.IEventPublisher
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Events.IEventPublisher`1
    name: IEventPublisher
    nameWithType: IEventPublisher
    fullName: Cqrs.Events.IEventPublisher
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.EventBus.Configuration
  isExternal: false
  name: Cqrs.Azure.EventHub.EventBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.EventBus.Configuration
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{`0}
  parent: Cqrs.Azure.EventHub.EventBus.Configuration
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
  name: AzureEventHubPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventHubPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
    name: AzureEventHubPublisherModule
    nameWithType: AzureEventHubPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
    name: AzureEventHubPublisherModule
    nameWithType: AzureEventHubPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}.Load
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{`0}.Load
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
  name: Load()
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.Load()
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken).Load()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).Load()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
    name: Load
    nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
    name: Load
    nameWithType: AzureEventHubPublisherModule(Of TAuthenticationToken).Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}.RegisterEventPublisher
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{`0}.RegisterEventPublisher
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
  name: RegisterEventPublisher()
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher()
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
    name: RegisterEventPublisher
    nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
    name: RegisterEventPublisher
    nameWithType: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}.RegisterEventMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{`0}.RegisterEventMessageSerialiser
  parent: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule{{TAuthenticationToken}}
  definition: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
  name: RegisterEventMessageSerialiser()
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
  isExternal: false
  name: AzureEventHubPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventHubPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
    name: AzureEventHubPublisherModule
    nameWithType: AzureEventHubPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
    name: AzureEventHubPublisherModule
    nameWithType: AzureEventHubPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
  isExternal: false
  name: Load()
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.Load()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.Load()
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken).Load()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).Load()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
    name: Load
    nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.Load
    name: Load
    nameWithType: AzureEventHubPublisherModule(Of TAuthenticationToken).Load
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
  isExternal: false
  name: RegisterEventPublisher()
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher()
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
    name: RegisterEventPublisher
    nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventPublisher
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventPublisher
    name: RegisterEventPublisher
    nameWithType: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventPublisher
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
  commentId: M:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
  isExternal: false
  name: RegisterEventMessageSerialiser()
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser()
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser()
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>.RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1.RegisterEventMessageSerialiser
    name: RegisterEventMessageSerialiser
    nameWithType: AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken).RegisterEventMessageSerialiser
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
