### YamlMime:ManagedReference
items:
- uid: Cqrs.Azure.EventHub.EventBus.Configuration
  commentId: N:Cqrs.Azure.EventHub.EventBus.Configuration
  id: Cqrs.Azure.EventHub.EventBus.Configuration
  children:
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
  - Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule`1
  langs:
  - csharp
  - vb
  name: Cqrs.Azure.EventHub.EventBus.Configuration
  nameWithType: Cqrs.Azure.EventHub.EventBus.Configuration
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration
  type: Namespace
  assemblies:
  - Cqrs.Azure.EventHub.EventBus
references:
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
  isExternal: false
  name: AzureEventHubPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventHubPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventHubPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventHubPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
    name: AzureEventHubPublisherModule
    nameWithType: AzureEventHubPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule`1
    name: AzureEventHubPublisherModule
    nameWithType: AzureEventHubPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
  isExternal: false
  name: AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
    name: AzureEventHubReceiverModule
    nameWithType: AzureEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule`1
    name: AzureEventHubReceiverModule
    nameWithType: AzureEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
  isExternal: false
  name: AzureEventBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureEventBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureEventBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureEventBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
    name: AzureEventBusReceiverModule
    nameWithType: AzureEventBusReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule`1
    name: AzureEventBusReceiverModule
    nameWithType: AzureEventBusReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule`1
  isExternal: false
  name: AzureEventBusPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventBusPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventBusPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventBusPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule`1
    name: AzureEventBusPublisherModule
    nameWithType: AzureEventBusPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule`1
    name: AzureEventBusPublisherModule
    nameWithType: AzureEventBusPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventBusPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
  isExternal: false
  name: AzureEventPublisherModule<TAuthenticationToken>
  nameWithType: AzureEventPublisherModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule<TAuthenticationToken>
  nameWithType.vb: AzureEventPublisherModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule(Of TAuthenticationToken)
  name.vb: AzureEventPublisherModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
    name: AzureEventPublisherModule
    nameWithType: AzureEventPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule`1
    name: AzureEventPublisherModule
    nameWithType: AzureEventPublisherModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureEventPublisherModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule`1
  isExternal: false
  name: AzureQueuedEventHubReceiverModule<TAuthenticationToken>
  nameWithType: AzureQueuedEventHubReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureQueuedEventHubReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule(Of TAuthenticationToken)
  name.vb: AzureQueuedEventHubReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule`1
    name: AzureQueuedEventHubReceiverModule
    nameWithType: AzureQueuedEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule`1
    name: AzureQueuedEventHubReceiverModule
    nameWithType: AzureQueuedEventHubReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventHubReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
  commentId: T:Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
  isExternal: false
  name: AzureQueuedEventBusReceiverModule<TAuthenticationToken>
  nameWithType: AzureQueuedEventBusReceiverModule<TAuthenticationToken>
  fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule<TAuthenticationToken>
  nameWithType.vb: AzureQueuedEventBusReceiverModule(Of TAuthenticationToken)
  fullName.vb: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule(Of TAuthenticationToken)
  name.vb: AzureQueuedEventBusReceiverModule(Of TAuthenticationToken)
  spec.csharp:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
    name: AzureQueuedEventBusReceiverModule
    nameWithType: AzureQueuedEventBusReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule
  - name: <
    nameWithType: <
    fullName: <
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule`1
    name: AzureQueuedEventBusReceiverModule
    nameWithType: AzureQueuedEventBusReceiverModule
    fullName: Cqrs.Azure.EventHub.EventBus.Configuration.AzureQueuedEventBusReceiverModule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TAuthenticationToken
    nameWithType: TAuthenticationToken
    fullName: TAuthenticationToken
  - name: )
    nameWithType: )
    fullName: )
