### YamlMime:ManagedReference
items:
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  id: TestAzureDocumentDbModule
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration
  children:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories
  langs:
  - csharp
  - vb
  name: TestAzureDocumentDbModule
  nameWithType: TestAzureDocumentDbModule
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  type: Class
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/TestAzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: TestAzureDocumentDbModule
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/TestAzureDocumentDbModule.cs
    startLine: 18
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nA <see cref=\"!:INinjectModule\"></see> that wires up <xref href=\"Cqrs.Ninject.Azure.DocumentDb.Factories.TestAzureDocumentDbDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref> as the\n<xref href=\"Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class TestAzureDocumentDbModule : AzureDocumentDbModule'
    content.vb: >-
      Public Class TestAzureDocumentDbModule
          Inherits AzureDocumentDbModule
  inheritance:
  - System.Object
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  inheritedMembers:
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  - Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories
  id: RegisterFactories
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule
  langs:
  - csharp
  - vb
  name: RegisterFactories()
  nameWithType: TestAzureDocumentDbModule.RegisterFactories()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories()
  type: Method
  source:
    remote:
      path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/TestAzureDocumentDbModule.cs
      branch: features/documentation
      repo: https://github.com/Chinchilla-Software-Com/CQRS.git
    id: RegisterFactories
    path: Framework/Ninject/Azure/Cqrs.Ninject.Azure.DocumentDb/Configuration/TestAzureDocumentDbModule.cs
    startLine: 23
  assemblies:
  - Cqrs.Ninject.Azure.DocumentDb
  namespace: Cqrs.Ninject.Azure.DocumentDb.Configuration
  summary: "\nRegister the all factories\n"
  example: []
  syntax:
    content: public override void RegisterFactories()
    content.vb: Public Overrides Sub RegisterFactories
  overridden: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  overload: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Cqrs.Ninject.Azure.DocumentDb.Factories.TestAzureDocumentDbDataStoreConnectionStringFactory
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Factories.TestAzureDocumentDbDataStoreConnectionStringFactory
  isExternal: false
  name: TestAzureDocumentDbDataStoreConnectionStringFactory
  nameWithType: TestAzureDocumentDbDataStoreConnectionStringFactory
  fullName: Cqrs.Ninject.Azure.DocumentDb.Factories.TestAzureDocumentDbDataStoreConnectionStringFactory
- uid: Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory
  commentId: T:Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory
  parent: Cqrs.Azure.DocumentDb.Factories
  isExternal: false
  name: IAzureDocumentDbDataStoreConnectionStringFactory
  nameWithType: IAzureDocumentDbDataStoreConnectionStringFactory
  fullName: Cqrs.Azure.DocumentDb.Factories.IAzureDocumentDbDataStoreConnectionStringFactory
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration
  commentId: N:Cqrs.Ninject.Azure.DocumentDb.Configuration
  isExternal: false
  name: Cqrs.Ninject.Azure.DocumentDb.Configuration
  nameWithType: Cqrs.Ninject.Azure.DocumentDb.Configuration
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  commentId: T:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration
  isExternal: false
  name: AzureDocumentDbModule
  nameWithType: AzureDocumentDbModule
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  isExternal: false
  name: Load()
  nameWithType: AzureDocumentDbModule.Load()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load()
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
    name: Load
    nameWithType: AzureDocumentDbModule.Load
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
    name: Load
    nameWithType: AzureDocumentDbModule.Load
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.Load
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  isExternal: false
  name: RegisterServices()
  nameWithType: AzureDocumentDbModule.RegisterServices()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices()
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
    name: RegisterServices
    nameWithType: AzureDocumentDbModule.RegisterServices
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
    name: RegisterServices
    nameWithType: AzureDocumentDbModule.RegisterServices
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterServices
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  isExternal: false
  name: RegisterCqrsRequirements()
  nameWithType: AzureDocumentDbModule.RegisterCqrsRequirements()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements()
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
    name: RegisterCqrsRequirements
    nameWithType: AzureDocumentDbModule.RegisterCqrsRequirements
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
    name: RegisterCqrsRequirements
    nameWithType: AzureDocumentDbModule.RegisterCqrsRequirements
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterCqrsRequirements
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  isExternal: false
  name: RegisterAzureHelpers()
  nameWithType: AzureDocumentDbModule.RegisterAzureHelpers()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers()
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
    name: RegisterAzureHelpers
    nameWithType: AzureDocumentDbModule.RegisterAzureHelpers
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
    name: RegisterAzureHelpers
    nameWithType: AzureDocumentDbModule.RegisterAzureHelpers
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterAzureHelpers
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Azure.DocumentDb.Factories
  commentId: N:Cqrs.Azure.DocumentDb.Factories
  isExternal: false
  name: Cqrs.Azure.DocumentDb.Factories
  nameWithType: Cqrs.Azure.DocumentDb.Factories
  fullName: Cqrs.Azure.DocumentDb.Factories
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  commentId: M:Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  parent: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule
  isExternal: false
  name: RegisterFactories()
  nameWithType: AzureDocumentDbModule.RegisterFactories()
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories()
  spec.csharp:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
    name: RegisterFactories
    nameWithType: AzureDocumentDbModule.RegisterFactories
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
    name: RegisterFactories
    nameWithType: AzureDocumentDbModule.RegisterFactories
    fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.AzureDocumentDbModule.RegisterFactories
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories*
  commentId: Overload:Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories
  isExternal: false
  name: RegisterFactories
  nameWithType: TestAzureDocumentDbModule.RegisterFactories
  fullName: Cqrs.Ninject.Azure.DocumentDb.Configuration.TestAzureDocumentDbModule.RegisterFactories
